require('./installMassiveMarketFallback');
const grokGold92Strategy=require('./scalpStrategies/grokGold92Strategy');
const proStrategy=require('./scalpStrategies/proStrategyMegaP1');
const goldRangeMrStrategy=require('./scalpStrategies/goldRangeMrMegaN4');
const goldRapidScalpStrategy=require('./scalpStrategies/goldRapidScalpStrategy');
const goldSweep5Strategy=require('./scalpStrategies/goldSweep5Strategy');
const goldExhaustionV3Strategy=require('./scalpStrategies/goldExhaustionV3Strategy');
const {getGoldCandlesResilient}=require('./goldCandleRecovery');
// Mega Optimizer winner G1: RSI 50/50, volume 1.10x, reward 0.60R.
Object.assign(grokGold92Strategy.CONFIG,{rsiBuyMin:50,rsiSellMax:50,volumeSpikeMult:1.10,rewardR:.6,sessionsUTC:[[0,24]]});
const STRATEGIES=[goldExhaustionV3Strategy,goldRapidScalpStrategy,grokGold92Strategy,proStrategy,goldRangeMrStrategy,goldSweep5Strategy];
function finiteOrNull(v){if(v===null||v===undefined||v==='')return null;const n=Number(v);return Number.isFinite(n)?n:null}function firstFiniteFrom(waits,keys){for(const w of waits)for(const k of keys){const v=finiteOrNull(w?.[k]);if(v!==null)return v}return null}function ema(values,p){const n=values.map(Number).filter(Number.isFinite);if(n.length<p)return null;const k=2/(p+1);let e=n[0];for(let i=1;i<n.length;i++)e=n[i]*k+e*(1-k);return e}function atr(rows,p=14){if(!Array.isArray(rows)||rows.length<p+1)return null;const s=rows.slice(-(p+1));let t=0;for(let i=1;i<s.length;i++){const h=finiteOrNull(s[i].high),l=finiteOrNull(s[i].low),pc=finiteOrNull(s[i-1].close);if([h,l,pc].some(v=>v===null))return null;t+=Math.max(h-l,Math.abs(h-pc),Math.abs(l-pc))}return t/p}function rollingVwap(rows,n=20){if(!Array.isArray(rows)||rows.length<n)return null;let pv=0,vol=0;for(const b of rows.slice(-n)){const h=finiteOrNull(b.high),l=finiteOrNull(b.low),c=finiteOrNull(b.close),v=finiteOrNull(b.volume);if([h,l,c,v].some(x=>x===null)||!(v>0))continue;pv+=((h+l+c)/3)*v;vol+=v}return vol?pv/vol:null}async function diagnostics(){try{const raw=await getGoldCandlesResilient('5min'),c=Array.isArray(raw)&&raw.length>1?raw.slice(0,-1):[];if(c.length<20)return{atr5:null,ema20:null,vwap5:null};return{atr5:atr(c),ema20:ema(c.map(x=>x.close),20),vwap5:rollingVwap(c)}}catch(e){return{atr5:null,ema20:null,vwap5:null}}}
async function scanGoldScalp(){const results=[];console.log('━━━━━━━━ GOLD LIVE STRATEGY CHECK ━━━━━━━━');for(const strategy of STRATEGIES){const label=strategy.CONFIG?.label||strategy.CONFIG?.id||'UNKNOWN';try{const result=await strategy.scan(),z=result||{ready:false,status:`${strategy.CONFIG?.id||'UNKNOWN'}_NO_RESULT`,pair:'XAUUSD'};results.push(z);console.log(z.ready?`🟢 ${label} → READY | ${z.direction} | ${z.status||'READY'} | score=${z.score}`:`🟡 ${label} → WAIT | ${z.status||'WAIT'}`)}catch(e){results.push({ready:false,status:`${strategy.CONFIG?.id||'UNKNOWN'}_ERROR`,pair:'XAUUSD',strategyId:strategy.CONFIG?.id,strategyLabel:label,error:e.message});console.log(`🔴 ${label} → ERROR | ${e.message}`)}}const readyResults=results.filter(x=>x?.ready),strategyChecks=results.map((w,i)=>({strategyId:STRATEGIES[i]?.CONFIG?.id||w?.strategyId||'UNKNOWN',strategyLabel:STRATEGIES[i]?.CONFIG?.label||w?.strategyLabel||'UNKNOWN',ready:Boolean(w?.ready),status:w?.status||'WAIT'}));if(readyResults.length){const selected=readyResults[0];console.log(`🏁 GOLD SCALP FINAL → ${readyResults.map(x=>`${x.strategyLabel}:${x.direction}`).join(' | ')} | ready=${readyResults.length}/${STRATEGIES.length}`);console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');return{...selected,strategyChecks,readyResults,readyStrategies:readyResults.map(x=>({strategyId:x.strategyId,strategyLabel:x.strategyLabel,direction:x.direction,status:x.status}))}}console.log('🏁 GOLD SCALP FINAL → WAIT | no M5 strategy ready');console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');const d=await diagnostics(),p=results[0]||{ready:false,status:'NO_SCALP_STRATEGY_READY',pair:'XAUUSD'};return{...p,strategyChecks,readyResults:[],atr5:finiteOrNull(p.atr5)??firstFiniteFrom(results,['atr5','atr'])??d.atr5,rsi5:finiteOrNull(p.rsi5)??firstFiniteFrom(results,['rsi5','rsi']),adx5:finiteOrNull(p.adx5)??firstFiniteFrom(results,['adx5','adx']),vwap5:finiteOrNull(p.vwap5)??firstFiniteFrom(results,['vwap5','vwap'])??d.vwap5,ema20:finiteOrNull(p.ema20)??firstFiniteFrom(results,['ema20'])??d.ema20}}
function buildReadyResult(s){return{pair:'XAUUSD',signal:{action:s.direction,entry:s.entry,stopLoss:s.stopLoss,targets:[s.tp1,s.tp2],confidence:Number(s.aiConfidence)>0?Number(s.aiConfidence):null,reason:`${s.strategyLabel} | ${s.entryMode} | Score ${s.score}/100`},indicators:{atr:s.atr5,rsi:s.rsi5,ema20:s.ema20,adx:s.adx5,vwap:s.vwap5},scalpMeta:s}}
async function buildGoldScalpResult(){const scalp=await scanGoldScalp();if(!scalp.ready)return{pair:'XAUUSD',signal:null,indicators:{atr:scalp.atr5??null,rsi:scalp.rsi5??null,ema20:scalp.ema20??null,adx:scalp.adx5??null,vwap:scalp.vwap5??null},scalpMeta:scalp,readySignalResults:[]};const ready=Array.isArray(scalp.readyResults)&&scalp.readyResults.length?scalp.readyResults:[scalp],readySignalResults=ready.map(x=>buildReadyResult({...x,strategyChecks:scalp.strategyChecks}));return{...readySignalResults[0],readySignalResults}}
module.exports={scanGoldScalp,buildGoldScalpResult};