const { getGoldHistoricalCandles } = require('./strategyHistory');

function num(v){const n=Number(v);return Number.isFinite(n)?n:null;}
function normalizeCandles(rows=[]){return rows.map(c=>({time:c.time??c.datetime??c.timestamp??c.date??null,open:num(c.open),high:num(c.high),low:num(c.low),close:num(c.close),volume:num(c.volume)||0})).filter(c=>[c.open,c.high,c.low,c.close].every(Number.isFinite)).sort((a,b)=>new Date(a.time||0)-new Date(b.time||0));}
function ema(values,p){const out=Array(values.length).fill(null);if(values.length<p)return out;let seed=0;for(let i=0;i<p;i++)seed+=values[i];let prev=seed/p;out[p-1]=prev;const k=2/(p+1);for(let i=p;i<values.length;i++){prev=values[i]*k+prev*(1-k);out[i]=prev;}return out;}
function rsi(values,p=14){const out=Array(values.length).fill(null);if(values.length<=p)return out;let g=0,l=0;for(let i=1;i<=p;i++){const d=values[i]-values[i-1];if(d>=0)g+=d;else l+=Math.abs(d);}let ag=g/p,al=l/p;const calc=()=>al===0?100:100-100/(1+ag/al);out[p]=calc();for(let i=p+1;i<values.length;i++){const d=values[i]-values[i-1];ag=(ag*(p-1)+(d>0?d:0))/p;al=(al*(p-1)+(d<0?Math.abs(d):0))/p;out[i]=calc();}return out;}
function atr(c,p=14){const tr=Array(c.length).fill(null),out=Array(c.length).fill(null);for(let i=1;i<c.length;i++)tr[i]=Math.max(c[i].high-c[i].low,Math.abs(c[i].high-c[i-1].close),Math.abs(c[i].low-c[i-1].close));if(c.length<=p)return out;let sum=0;for(let i=1;i<=p;i++)sum+=tr[i];let prev=sum/p;out[p]=prev;for(let i=p+1;i<c.length;i++){prev=(prev*(p-1)+tr[i])/p;out[i]=prev;}return out;}
function adx(c,p=14){const n=c.length,pdm=Array(n).fill(0),mdm=Array(n).fill(0),tr=Array(n).fill(0),dx=Array(n).fill(null),out=Array(n).fill(null);for(let i=1;i<n;i++){const up=c[i].high-c[i-1].high,down=c[i-1].low-c[i].low;pdm[i]=up>down&&up>0?up:0;mdm[i]=down>up&&down>0?down:0;tr[i]=Math.max(c[i].high-c[i].low,Math.abs(c[i].high-c[i-1].close),Math.abs(c[i].low-c[i-1].close));}if(n<=p*2)return out;let ts=0,ps=0,ms=0;for(let i=1;i<=p;i++){ts+=tr[i];ps+=pdm[i];ms+=mdm[i];}for(let i=p;i<n;i++){if(i>p){ts=ts-ts/p+tr[i];ps=ps-ps/p+pdm[i];ms=ms-ms/p+mdm[i];}if(!ts)continue;const plus=100*ps/ts,minus=100*ms/ts,sum=plus+minus;if(sum)dx[i]=100*Math.abs(plus-minus)/sum;}const first=p*2-1;let sum=0,count=0;for(let i=p;i<=first;i++)if(dx[i]!=null){sum+=dx[i];count++;}if(!count)return out;let prev=sum/count;out[first]=prev;for(let i=first+1;i<n;i++){if(dx[i]==null)continue;prev=(prev*(p-1)+dx[i])/p;out[i]=prev;}return out;}
function vwap(c){const out=Array(c.length).fill(null);let pv=0,v=0;for(let i=0;i<c.length;i++){const vol=Number(c[i].volume)||0;if(vol>0){pv+=((c[i].high+c[i].low+c[i].close)/3)*vol;v+=vol;}out[i]=v>0?pv/v:null;}return out;}
function macd(values,fast=12,slow=26,signal=9){const ef=ema(values,fast),es=ema(values,slow),line=values.map((_,i)=>ef[i]!=null&&es[i]!=null?ef[i]-es[i]:null);const clean=line.map(v=>v==null?0:v);const sig=ema(clean,signal);const signalLine=sig.map((v,i)=>line[i]==null?null:v);return {line,signal:signalLine};}

const DEFAULT_STRATEGY={timeframe:'15min',direction:'BUY',conditions:[],slAtr:1.2,tpAtr:2,historyCount:2000};
const LABELS={
 close_above_ema:c=>`إغلاق الشمعة فوق EMA ${c.period}`,
 close_below_ema:c=>`إغلاق الشمعة تحت EMA ${c.period}`,
 ema_cross_up:c=>`EMA ${c.fast} يعبر أعلى EMA ${c.slow}`,
 ema_cross_down:c=>`EMA ${c.fast} يعبر أسفل EMA ${c.slow}`,
 rsi_above:c=>`RSI(14) أكبر من ${c.value}`,
 rsi_below:c=>`RSI(14) أقل من ${c.value}`,
 adx_above:c=>`ADX(14) أكبر من ${c.value}`,
 close_above_vwap:()=>`إغلاق الشمعة فوق VWAP`,
 close_below_vwap:()=>`إغلاق الشمعة تحت VWAP`,
 macd_cross_up:()=>`MACD يعبر أعلى Signal`,
 macd_cross_down:()=>`MACD يعبر أسفل Signal`,
 bullish_candle:()=>`الشمعة صاعدة (Close > Open)`,
 bearish_candle:()=>`الشمعة هابطة (Close < Open)`,
 close_above_prev_high:()=>`الإغلاق فوق High الشمعة السابقة`,
 close_below_prev_low:()=>`الإغلاق تحت Low الشمعة السابقة`
};
function conditionLabel(c){return LABELS[c.type]?.(c)||c.type;}
function buildIndicators(candles,conditions){const closes=candles.map(c=>c.close),periods=new Set([20]);for(const c of conditions){if(c.period)periods.add(Number(c.period));if(c.fast)periods.add(Number(c.fast));if(c.slow)periods.add(Number(c.slow));}const emas={};for(const p of periods)emas[p]=ema(closes,p);return {emas,rsi14:rsi(closes,14),adx14:adx(candles,14),atr14:atr(candles,14),vwap:vwap(candles),macd:macd(closes)};}
function evaluateCondition(cond,i,c,ind){switch(cond.type){case'close_above_ema':return ind.emas[cond.period]?.[i]!=null&&c[i].close>ind.emas[cond.period][i];case'close_below_ema':return ind.emas[cond.period]?.[i]!=null&&c[i].close<ind.emas[cond.period][i];case'ema_cross_up':return i>0&&ind.emas[cond.fast]?.[i]!=null&&ind.emas[cond.slow]?.[i]!=null&&ind.emas[cond.fast][i]>ind.emas[cond.slow][i]&&ind.emas[cond.fast][i-1]<=ind.emas[cond.slow][i-1];case'ema_cross_down':return i>0&&ind.emas[cond.fast]?.[i]!=null&&ind.emas[cond.slow]?.[i]!=null&&ind.emas[cond.fast][i]<ind.emas[cond.slow][i]&&ind.emas[cond.fast][i-1]>=ind.emas[cond.slow][i-1];case'rsi_above':return ind.rsi14[i]!=null&&ind.rsi14[i]>Number(cond.value);case'rsi_below':return ind.rsi14[i]!=null&&ind.rsi14[i]<Number(cond.value);case'adx_above':return ind.adx14[i]!=null&&ind.adx14[i]>Number(cond.value);case'close_above_vwap':return ind.vwap[i]!=null&&c[i].close>ind.vwap[i];case'close_below_vwap':return ind.vwap[i]!=null&&c[i].close<ind.vwap[i];case'macd_cross_up':return i>0&&ind.macd.line[i]!=null&&ind.macd.signal[i]!=null&&ind.macd.line[i]>ind.macd.signal[i]&&ind.macd.line[i-1]<=ind.macd.signal[i-1];case'macd_cross_down':return i>0&&ind.macd.line[i]!=null&&ind.macd.signal[i]!=null&&ind.macd.line[i]<ind.macd.signal[i]&&ind.macd.line[i-1]>=ind.macd.signal[i-1];case'bullish_candle':return c[i].close>c[i].open;case'bearish_candle':return c[i].close<c[i].open;case'close_above_prev_high':return i>0&&c[i].close>c[i-1].high;case'close_below_prev_low':return i>0&&c[i].close<c[i-1].low;default:return false;}}

async function backtestGoldStrategy(input={}){const s={...DEFAULT_STRATEGY,...input,conditions:Array.isArray(input.conditions)?input.conditions:[]};if(!s.conditions.length)throw new Error('أضف شرطًا واحدًا على الأقل قبل الاختبار.');const raw=await getGoldHistoricalCandles(s.timeframe,s.historyCount);const candles=normalizeCandles(raw);if(candles.length<60)throw new Error(`عدد شموع XAUUSD غير كافٍ: ${candles.length}`);const ind=buildIndicators(candles,s.conditions);const trades=[];for(let i=35;i<candles.length-2;){if(ind.atr14[i]==null){i++;continue;}const signal=s.conditions.every(cond=>evaluateCondition(cond,i,candles,ind));if(!signal){i++;continue;}const side=s.direction==='SELL'?'SELL':'BUY',entryIndex=i+1,entry=candles[entryIndex].open,risk=ind.atr14[i]*Number(s.slAtr||1.2),reward=ind.atr14[i]*Number(s.tpAtr||2),sl=side==='BUY'?entry-risk:entry+risk,tp=side==='BUY'?entry+reward:entry-reward;let exitIndex=null,result=null;for(let j=entryIndex;j<candles.length;j++){const bar=candles[j];if(side==='BUY'){if(bar.low<=sl){result='LOSS';exitIndex=j;break;}if(bar.high>=tp){result='WIN';exitIndex=j;break;}}else{if(bar.high>=sl){result='LOSS';exitIndex=j;break;}if(bar.low<=tp){result='WIN';exitIndex=j;break;}}}if(!result)break;trades.push({side,result,entry,sl,tp,signalTime:candles[i].time,exitTime:candles[exitIndex].time,rMultiple:result==='WIN'?Number(s.tpAtr||2)/Number(s.slAtr||1.2):-1});i=Math.max(i+1,exitIndex+1);}const wins=trades.filter(t=>t.result==='WIN').length,losses=trades.length-wins,netR=trades.reduce((a,t)=>a+t.rMultiple,0);let eq=0,peak=0,maxDD=0,ws=0,ls=0,bws=0,wls=0;for(const t of trades){eq+=t.rMultiple;peak=Math.max(peak,eq);maxDD=Math.max(maxDD,peak-eq);if(t.result==='WIN'){ws++;ls=0;bws=Math.max(bws,ws);}else{ls++;ws=0;wls=Math.max(wls,ls);}}return {pair:'XAUUSD',strategy:s,candles:candles.length,from:candles[0]?.time,to:candles.at(-1)?.time,trades,total:trades.length,wins,losses,winRate:trades.length?wins/trades.length*100:0,netR,maxDrawdownR:maxDD,bestWinStreak:bws,worstLossStreak:wls};}
module.exports={DEFAULT_STRATEGY,conditionLabel,backtestGoldStrategy};
