'use strict';
const {getGoldCandlesResilient}=require('../goldCandleRecovery');
const {getPrice}=require('../marketService');
const CONFIG={id:'GOLD_MICRO_PULLBACK',label:'⚡ Gold Micro Pullback',pair:'XAUUSD',fast:9,slow:21,trend:50,impulseBars:2,impulseAtr:1.2,pullbackBars:2,pullbackMin:.12,pullbackMax:.45,bodyMin:.55,closePos:.62,sepAtr:.08,slAtr:1.1,rr:.7,maxBars:10,cooldown:1,h0:10,h1:19};
const STATE={lastSignalBar:null};
const finite=v=>{const n=Number(v);return Number.isFinite(n)?n:null};
function closed(r){return Array.isArray(r)&&r.length>1?r.slice(0,-1):[]}
function ema(c,p){const a=Array(c.length).fill(NaN),k=2/(p+1);let x=+c[0].close;for(let i=0;i<c.length;i++){x=i?+c[i].close*k+x*(1-k):x;a[i]=x}return a}
function atr(c,p=14){const a=Array(c.length).fill(NaN);for(let i=p;i<c.length;i++){let s=0;for(let j=i-p+1;j<=i;j++)s+=Math.max(c[j].high-c[j].low,Math.abs(c[j].high-c[j-1].close),Math.abs(c[j].low-c[j-1].close));a[i]=s/p}return a}
function wait(status,extra={}){return{ready:false,status,pair:CONFIG.pair,strategyId:CONFIG.id,strategyLabel:CONFIG.label,...extra}}
async function scan(){const[raw,liveRaw]=await Promise.all([getGoldCandlesResilient('5min',180),getPrice('XAUUSD')]);const c=closed(raw);if(c.length<60)return wait('MICRO_NO_DATA',{m5:c.length});const i=c.length-1,b=c[i],A=atr(c),E9=ema(c,9),E21=ema(c,21),E50=ema(c,50),a=A[i];if(![a,E9[i],E21[i],E50[i],E21[i-3]].every(Number.isFinite)||!(a>0))return wait('MICRO_INDICATORS_NOT_READY');const hour=new Date(b.timestamp).getUTCHours();if(hour<CONFIG.h0||hour>CONFIG.h1)return wait('MICRO_OUTSIDE_SESSION',{hourUTC:hour});const range=b.high-b.low,body=Math.abs(b.close-b.open);if(!(range>0)||body/range<CONFIG.bodyMin)return wait('MICRO_BODY_TOO_SMALL');if(Math.abs(E9[i]-E21[i])/a<CONFIG.sepAtr)return wait('MICRO_EMA_SEPARATION_LOW');let side=null;if(E9[i]>E21[i]&&E21[i]>E50[i]&&E21[i]>E21[i-3])side='BUY';else if(E9[i]<E21[i]&&E21[i]<E50[i]&&E21[i]<E21[i-3])side='SELL';if(!side)return wait('MICRO_NO_TREND');const is=i-CONFIG.pullbackBars-CONFIG.impulseBars,ie=i-CONFIG.pullbackBars;if(is<1)return wait('MICRO_NO_HISTORY');const impulse=side==='BUY'?c[ie].close-c[is].open:c[is].open-c[ie].close;if(impulse<CONFIG.impulseAtr*a)return wait('MICRO_IMPULSE_TOO_SMALL');let ph=-Infinity,pl=Infinity;for(let j=ie+1;j<i;j++){ph=Math.max(ph,c[j].high);pl=Math.min(pl,c[j].low)}const retr=side==='BUY'?(c[ie].close-pl)/impulse:(ph-c[ie].close)/impulse;if(retr<CONFIG.pullbackMin||retr>CONFIG.pullbackMax)return wait('MICRO_PULLBACK_OUT_OF_RANGE',{retrace:retr});const pos=(b.close-b.low)/range;if(side==='BUY'&&(pos<CONFIG.closePos||b.close<=c[i-1].high))return wait('MICRO_NO_BUY_CONFIRM');if(side==='SELL'&&(pos>1-CONFIG.closePos||b.close>=c[i-1].low))return wait('MICRO_NO_SELL_CONFIRM');const signalBar=String(b.timestamp);if(STATE.lastSignalBar===signalBar)return wait('MICRO_SIGNAL_ALREADY_SENT');const entry=finite(liveRaw);if(entry===null)return wait('MICRO_NO_LIVE_PRICE');const risk=CONFIG.slAtr*a,stopLoss=side==='BUY'?entry-risk:entry+risk,tp=side==='BUY'?entry+risk*CONFIG.rr:entry-risk*CONFIG.rr;return{ready:true,status:'MICRO_READY',pair:CONFIG.pair,direction:side,strategyId:CONFIG.id,strategyLabel:CONFIG.label,entryMode:'M5_MICRO_PULLBACK_CONTINUATION',grade:'A',score:90,aiConfidence:0,entry,stopLoss,tp1:tp,tp2:tp,risk,rrTp1:CONFIG.rr,rrTp2:CONFIG.rr,atr5:a,ema20:E21[i],hourUTC:hour,signalBar,maxBars:CONFIG.maxBars,reasons:['Fixed validated Micro Pullback candidate','EMA9/21/50 continuation regime','2-bar impulse + 2-bar pullback','confirmation break','RR 0.70']}}
function markSent(meta){const bar=String(meta?.signalBar||meta||'').trim();if(bar)STATE.lastSignalBar=bar}
module.exports={CONFIG,scan,markSent};
