'use strict';
const {getGoldCandlesResilient}=require('../goldCandleRecovery');
const {getPrice}=require('../marketService');
const CONFIG={id:'GOLD_VOLATILITY_TRANSITION',label:'⚡ Gold Volatility Transition',pair:'XAUUSD',base:60,comp:5,squeeze:.62,expand:.95,body:.45,sl:1,rangeRisk:.5,rr:1.6,maxBars:14,cooldown:2,blockedUtcHours:new Set([4])};
const STATE={lastSignalBar:null};
const finite=v=>{const n=Number(v);return Number.isFinite(n)?n:null};
function closed(r){return Array.isArray(r)&&r.length>1?r.slice(0,-1):[]}
function atr(c,p=14){const a=Array(c.length).fill(NaN),q=[];let s=0;for(let i=1;i<c.length;i++){const t=Math.max(+c[i].high-+c[i].low,Math.abs(+c[i].high-+c[i-1].close),Math.abs(+c[i].low-+c[i-1].close));q.push(t);s+=t;if(q.length>p)s-=q.shift();if(q.length===p)a[i]=s/p}return a}
function wait(status,extra={}){return{ready:false,status,pair:CONFIG.pair,strategyId:CONFIG.id,strategyLabel:CONFIG.label,...extra}}
async function scan(){const[raw,liveRaw]=await Promise.all([getGoldCandlesResilient('5min',220),getPrice('XAUUSD')]);const c=closed(raw);if(c.length<100)return wait('VTRANS_NO_DATA',{m5:c.length});const A=atr(c),i=c.length-1,b=c[i],a=A[i];if(!(a>0))return wait('VTRANS_ATR_NOT_READY');const hour=new Date(b.timestamp).getUTCHours();if(CONFIG.blockedUtcHours.has(hour))return wait('VTRANS_BLOCKED_HOUR',{hourUTC:hour});const old=A.slice(i-CONFIG.base-CONFIG.comp,i-CONFIG.comp).filter(Number.isFinite),rec=A.slice(i-CONFIG.comp,i).filter(Number.isFinite);if(old.length<CONFIG.base*.8||rec.length<CONFIG.comp)return wait('VTRANS_HISTORY_NOT_READY');const baseline=old.reduce((x,y)=>x+y,0)/old.length,recent=rec.reduce((x,y)=>x+y,0)/rec.length,squeeze=recent/baseline;if(squeeze>CONFIG.squeeze)return wait('VTRANS_NO_COMPRESSION',{squeeze});const range=+b.high-+b.low,body=Math.abs(+b.close-+b.open),bodyRatio=range>0?body/range:0;if(!(range>0)||range/a<CONFIG.expand)return wait('VTRANS_NO_EXPANSION',{expandRatio:range/a});if(bodyRatio<CONFIG.body)return wait('VTRANS_BODY_TOO_SMALL',{bodyRatio});let hi=-Infinity,lo=Infinity;for(let j=i-CONFIG.comp;j<i;j++){hi=Math.max(hi,+c[j].high);lo=Math.min(lo,+c[j].low)}let side=null;if(+b.close>hi)side='BUY';else if(+b.close<lo)side='SELL';if(!side)return wait('VTRANS_NO_BOX_BREAK',{boxHigh:hi,boxLow:lo});const signalBar=String(b.timestamp);if(STATE.lastSignalBar===signalBar)return wait('VTRANS_SIGNAL_ALREADY_SENT');const entry=finite(liveRaw);if(entry===null)return wait('VTRANS_NO_LIVE_PRICE');const risk=Math.max(a*CONFIG.sl,(hi-lo)*CONFIG.rangeRisk),stopLoss=side==='BUY'?entry-risk:entry+risk,tp=side==='BUY'?entry+risk*CONFIG.rr:entry-risk*CONFIG.rr;return{ready:true,status:'VTRANS_READY',pair:CONFIG.pair,direction:side,strategyId:CONFIG.id,strategyLabel:CONFIG.label,entryMode:'M5_VOLATILITY_TRANSITION',grade:'A',score:90,aiConfidence:0,entry,stopLoss,tp1:tp,tp2:tp,risk,rrTp1:CONFIG.rr,rrTp2:CONFIG.rr,atr5:a,hourUTC:hour,signalBar,maxBars:CONFIG.maxBars,reasons:['Validated compression-to-expansion transition','ATR compression <= 0.62 baseline','Expansion >= 0.95 ATR','Body >= 45% of candle range','5-bar compression box break','RR 1.60','UTC 04 excluded by train-only filter']}}
function markSent(meta){const bar=String(meta?.signalBar||meta||'').trim();if(bar)STATE.lastSignalBar=bar}
module.exports={CONFIG,scan,markSent};
