'use strict';
const {getGoldCandlesResilient}=require('../goldCandleRecovery');
const {getPrice}=require('../marketService');
// Q15 locked candidate — parity module only until final live integration is approved.
// BUY-only failed bearish expansion: BIG>=1.5 ATR, impulse body>=.60, reclaim=.30 ATR,
// bullish confirmation close-position>=.65, ATR regime .75..2, block UTC 06/07/08, SL=1 ATR, TP=1.5 ATR, maxBars=12.
const CONFIG={id:'GOLD_FAILED_MOVE_Q15',label:'🔄 Gold Failed Move Q15',pair:'XAUUSD',bigAtr:1.5,impulseBodyMin:.60,reclaimAtr:.30,confirmClosePos:.65,atrRatioMin:.75,atrRatioMax:2,blockedHoursUTC:[6,7,8],slAtr:1,rr:1.5,maxBars:12};
const STATE={lastSignalBar:null};
const finite=v=>{const n=Number(v);return Number.isFinite(n)?n:null};
function closed(r){return Array.isArray(r)&&r.length>1?r.slice(0,-1):[]}
function atr(c,p=14){const a=Array(c.length).fill(NaN);for(let i=p;i<c.length;i++){let s=0;for(let j=i-p+1;j<=i;j++)s+=Math.max(c[j].high-c[j].low,Math.abs(c[j].high-c[j-1].close),Math.abs(c[j].low-c[j-1].close));a[i]=s/p}return a}
function atrAvg(A,i,n=50){if(i<n)return NaN;let s=0,c=0;for(let j=i-n;j<i;j++)if(Number.isFinite(A[j])){s+=A[j];c++}return c===n?s/n:NaN}
function wait(status,extra={}){return{ready:false,status,pair:CONFIG.pair,strategyId:CONFIG.id,strategyLabel:CONFIG.label,...extra}}
async function scan(){const[raw,liveRaw]=await Promise.all([getGoldCandlesResilient('5min',180),getPrice('XAUUSD')]);const c=closed(raw);if(c.length<70)return wait('Q15_NO_DATA',{m5:c.length});const i=c.length-1,b=c[i],x=c[i-1],A=atr(c),a=A[i],aa=atrAvg(A,i);if(!(Number.isFinite(a)&&a>0&&Number.isFinite(aa)&&aa>0))return wait('Q15_INDICATORS_NOT_READY');const hour=new Date(b.timestamp).getUTCHours();if(CONFIG.blockedHoursUTC.includes(hour))return wait('Q15_BLOCKED_UTC_HOUR',{hourUTC:hour});const xr=x.high-x.low,br=b.high-b.low;if(!(xr>0&&br>0))return wait('Q15_BAD_RANGE');if(x.close>=x.open)return wait('Q15_NO_BEARISH_EXPANSION');if(xr/a<CONFIG.bigAtr)return wait('Q15_EXPANSION_TOO_SMALL',{expansionAtr:xr/a});if(Math.abs(x.close-x.open)/xr<CONFIG.impulseBodyMin)return wait('Q15_IMPULSE_BODY_TOO_SMALL');if(!(b.close>x.open&&b.high>x.high-CONFIG.reclaimAtr*a))return wait('Q15_RECLAIM_FAILED');if(b.close<=b.open)return wait('Q15_CONFIRM_NOT_BULLISH');const cp=(b.close-b.low)/br;if(cp<CONFIG.confirmClosePos)return wait('Q15_CONFIRM_CLOSE_POSITION_LOW',{closePos:cp});const ar=a/aa;if(ar<CONFIG.atrRatioMin||ar>CONFIG.atrRatioMax)return wait('Q15_ATR_REGIME',{atrRatio:ar});const signalBar=String(b.timestamp);if(STATE.lastSignalBar===signalBar)return wait('Q15_SIGNAL_ALREADY_SENT');const entry=finite(liveRaw);if(entry===null)return wait('Q15_NO_LIVE_PRICE');const risk=CONFIG.slAtr*a,stopLoss=entry-risk,tp=entry+risk*CONFIG.rr;return{ready:true,status:'Q15_READY',pair:CONFIG.pair,direction:'BUY',strategyId:CONFIG.id,strategyLabel:CONFIG.label,entryMode:'M5_FAILED_MOVE_REVERSAL_Q15',grade:'A',score:92,aiConfidence:0,entry,stopLoss,tp1:tp,tp2:tp,risk,rrTp1:CONFIG.rr,rrTp2:CONFIG.rr,atr5:a,hourUTC:hour,signalBar,maxBars:CONFIG.maxBars,reasons:['Q15 BUY-only failed bearish expansion','Expansion >= 1.50 ATR','Impulse body >= 0.60','Reclaim >= 0.30 ATR','Bullish confirmation close position >= 0.65','ATR regime 0.75-2.00','UTC 06/07/08 blocked','SL 1 ATR','TP 1.5 ATR','RR 1:1.5']}}
function markSent(meta){const bar=String(meta?.signalBar||meta||'').trim();if(bar)STATE.lastSignalBar=bar}
module.exports={CONFIG,scan,markSent};