const { getCandles, getPrice } = require('../marketService');

const CONFIG = { id:'NEW_YORK', label:'🗽 New York Strategy', pair:'XAUUSD', sessionStartMinutes:510, sessionEndMinutes:720, adx15Min:24, chaseAtrMax:.20, touchToleranceAtr:.12, confirmationBodyAtrMax:.20, momentumMin:2, swingLookback:12, slBufferAtr:.15, minRiskAtr:.55, tp1R:1.50, tp2R:1.50 };
function n(v){v=Number(v);return Number.isFinite(v)?v:null} function closed(a){return Array.isArray(a)&&a.length>1?a.slice(0,-1):[]} function cls(a){return a.map(x=>n(x.close)).filter(x=>x!=null)}
function ema(a,p){if(a.length<p)return null;let e=a.slice(0,p).reduce((x,y)=>x+y,0)/p,k=2/(p+1);for(let i=p;i<a.length;i++)e=a[i]*k+e*(1-k);return e}
function atr(a,p=14){if(a.length<p+1)return null;let s=0,z=a.slice(-(p+1));for(let i=1;i<z.length;i++){let h=n(z[i].high),l=n(z[i].low),pc=n(z[i-1].close);if([h,l,pc].some(x=>x==null))return null;s+=Math.max(h-l,Math.abs(h-pc),Math.abs(l-pc))}return s/p}
function rsi(a,p=14){if(a.length<p+1)return null;let g=0,l=0;for(let i=a.length-p;i<a.length;i++){let d=a[i]-a[i-1];d>=0?g+=d:l-=d}return l===0?100:100-100/(1+g/l)}
function adx(a,p=14){if(a.length<p*2+1)return null;let z=a.slice(-(p*2+1)),tr=[],pd=[],md=[];for(let i=1;i<z.length;i++){let h=n(z[i].high),l=n(z[i].low),ph=n(z[i-1].high),pl=n(z[i-1].low),pc=n(z[i-1].close);if([h,l,ph,pl,pc].some(x=>x==null))return null;let u=h-ph,d=pl-l;pd.push(u>d&&u>0?u:0);md.push(d>u&&d>0?d:0);tr.push(Math.max(h-l,Math.abs(h-pc),Math.abs(l-pc)))}let dx=[];for(let e=p;e<=tr.length;e++){let st=e-p,T=tr.slice(st,e).reduce((x,y)=>x+y,0);if(!T)continue;let P=100*pd.slice(st,e).reduce((x,y)=>x+y,0)/T,M=100*md.slice(st,e).reduce((x,y)=>x+y,0)/T;if(P+M)dx.push(100*Math.abs(P-M)/(P+M))}let t=dx.slice(-p);return t.length?t.reduce((x,y)=>x+y,0)/t.length:null}
function vwap(a){let z=a.slice(-24),pv=0,v=0;for(let c of z){let h=n(c.high),l=n(c.low),cl=n(c.close),q=n(c.volume);if(h!=null&&l!=null&&cl!=null&&q>0){pv+=(h+l+cl)/3*q;v+=q}}return v?pv/v:null}
function trend(a){let c=cls(a),a20=ema(c,20),a50=ema(c,50);return a20==null||a50==null?null:a20>a50?'BUY':a20<a50?'SELL':null}
function session(){let p=new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',hour12:false,hour:'2-digit',minute:'2-digit'}).formatToParts(new Date()),g=t=>Number(p.find(x=>x.type===t)?.value||0),m=g('hour')*60+g('minute');return m>=CONFIG.sessionStartMinutes&&m<CONFIG.sessionEndMinutes}
async function scan(){let base={pair:CONFIG.pair,strategyId:CONFIG.id,strategyLabel:CONFIG.label};if(!session())return{...base,ready:false,status:'NY_OUTSIDE_SESSION'};let[r5,r15,r1h,px]=await Promise.all([getCandles('XAUUSD','5min'),getCandles('XAUUSD','15min'),getCandles('XAUUSD','1h'),getPrice('XAUUSD')]),c5=closed(r5),c15=closed(r15),c1=closed(r1h);if(c5.length<40||c15.length<55||c1.length<55)return{...base,ready:false,status:'NY_NO_DATA'};let t15=trend(c15),t1=trend(c1),a15=adx(c15);if(!t15||t15!==t1)return{...base,ready:false,status:'NY_REGIME_MISMATCH'};if(!(a15>=CONFIG.adx15Min))return{...base,ready:false,status:'NY_ADX15_TOO_WEAK'};let side=t15,C=cls(c5),A=atr(c5),R=rsi(C),E=ema(C,20),V=vwap(c5),last=c5.at(-1),lc=n(last.close),lo=n(last.open);if([A,E,V,lc,lo].some(x=>x==null)||!(A>0))return{...base,ready:false,status:'NY_INDICATORS_NOT_READY'};let dist=Math.min(Math.abs(lc-E),Math.abs(lc-V))/A;if(dist>CONFIG.chaseAtrMax)return{...base,ready:false,status:'NY_ANTI_CHASE'};let rec=c5.slice(-4),tol=A*CONFIG.touchToleranceAtr,touch=rec.some(x=>n(x.low)<=E+tol&&n(x.high)>=E-tol)||rec.some(x=>n(x.low)<=V+tol&&n(x.high)>=V-tol);if(!touch)return{...base,ready:false,status:'NY_NO_PULLBACK_TOUCH'};if(!(side==='BUY'?lc>lo&&(lc>=E||lc>=V):lc<lo&&(lc<=E||lc<=V)))return{...base,ready:false,status:'NY_CONFIRMATION_NOT_READY'};let z=c5.slice(-3),imp=z.reduce((s,x)=>s+(n(x.close)-n(x.open)),0),str=Math.abs(z.reduce((s,x)=>s+(n(x.close)>n(x.open)?1:n(x.close)<n(x.open)?-1:0),0)),md=imp>0?'BUY':imp<0?'SELL':null;if(md!==side||str<2)return{...base,ready:false,status:'NY_MOMENTUM_NOT_RETURNED'};let body=Math.abs(lc-lo)/A;if(body>.20)return{...base,ready:false,status:'NY_EXECUTION_CANDLE_TOO_LARGE'};let entry=n(px)??lc,live=Math.min(Math.abs(entry-E),Math.abs(entry-V))/A;if(live>.20)return{...base,ready:false,status:'NY_LIVE_ANTI_CHASE'};let vals=c5.slice(-12).map(x=>n(side==='BUY'?x.low:x.high)).filter(x=>x!=null),sw=side==='BUY'?Math.min(...vals):Math.max(...vals),raw=side==='BUY'?entry-(sw+A*.15):(sw+A*.15)-entry,risk=Math.max(raw,A*.55),sl=side==='BUY'?entry-risk:entry+risk,tp=side==='BUY'?entry+risk*1.5:entry-risk*1.5,score=Math.min(100,70+(a15>=25?8:5)+(live<=.20?10:6)+Math.min(8,str*2));return{...base,ready:true,status:'NY_READY',direction:side,entryMode:'REGIME_PULLBACK',grade:'A',score,aiConfidence:0,entry,stopLoss:sl,tp1:tp,tp2:tp,risk,rrTp1:1.5,rrTp2:1.5,atr5:A,rsi5:R,adx5:adx(c5),adx15:a15,trend15:t15,trend1h:t1,ema20:E,vwap5:V,reasons:['NY session','H1 + 15M aligned','ADX15 >= 24','5M pullback','anti-chase <= 0.20 ATR']}}
module.exports={CONFIG,scan,markSent(){}};
