require('dotenv').config();
const fs=require('fs'),path=require('path');
const {getGoldHistoricalCandles}=require('./backtestHistoryDukascopyLocal');
const H=Math.max(10000,Math.min(100000,Number(process.env.BACKTEST_HISTORY||100000)));
const SPREAD=Math.max(0,Number(process.env.BACKTEST_SPREAD_USD||0.35)),SLIP=Math.max(0,Number(process.env.BACKTEST_SLIPPAGE_USD||0.05));
const OUT=path.resolve(process.cwd(),'data','backtests');fs.mkdirSync(OUT,{recursive:true});
function agg(c,m){const z=m*60000,o=[];let x=null;for(const r of c){const b=Math.floor(r.time/z)*z;if(!x||x.time!==b){if(x)o.push(x);x={time:b,open:r.open,high:r.high,low:r.low,close:r.close}}else{x.high=Math.max(x.high,r.high);x.low=Math.min(x.low,r.low);x.close=r.close}}if(x)o.push(x);return o}
function ema(v,p){const o=Array(v.length).fill(null);if(v.length<p)return o;let s=0;for(let i=0;i<p;i++)s+=v[i];let e=s/p;o[p-1]=e;const k=2/(p+1);for(let i=p;i<v.length;i++){e=v[i]*k+e*(1-k);o[i]=e}return o}
function atr(c,p=14){const tr=Array(c.length).fill(0),o=Array(c.length).fill(null);for(let i=1;i<c.length;i++)tr[i]=Math.max(c[i].high-c[i].low,Math.abs(c[i].high-c[i-1].close),Math.abs(c[i].low-c[i-1].close));let s=0;for(let i=1;i<=p;i++)s+=tr[i];let a=s/p;o[p]=a;for(let i=p+1;i<c.length;i++){a=(a*(p-1)+tr[i])/p;o[i]=a}return o}
function stats(t){if(!t.length)return{trades:0,wr:0,netR:0,avgR:0,pf:0,dd:0,maxLS:0};let w=0,gw=0,gl=0,e=0,pk=0,dd=0,ls=0,ml=0;for(const x of t){e+=x.r;if(x.r>0){w++;gw+=x.r;ls=0}else{gl+=Math.abs(x.r);ls++;ml=Math.max(ml,ls)}pk=Math.max(pk,e);dd=Math.max(dd,pk-e)}return{trades:t.length,wr:w/t.length*100,netR:e,avgR:e/t.length,pf:gl?gw/gl:999,dd,maxLS:ml}}
const fmt=s=>`${s.trades} trades | WR ${s.wr.toFixed(1)}% | Net ${s.netR>=0?'+':''}${s.netR.toFixed(2)}R | Avg ${s.avgR.toFixed(3)}R | PF ${s.pf.toFixed(2)} | DD ${s.dd.toFixed(2)}R | LS ${s.maxLS}`;
function signal(c,i,e50,a){if(i<55||![e50[i],a[i]].every(Number.isFinite))return null;let hi=-Infinity,lo=Infinity;for(let k=i-20;k<i;k++){hi=Math.max(hi,c[k].high);lo=Math.min(lo,c[k].low)}const buf=.1*a[i],maxExt=1.25*a[i];const buy=c[i].close>hi+buf&&c[i].close>e50[i]&&c[i].close-e50[i]<=maxExt;const sell=c[i].close<lo-buf&&c[i].close<e50[i]&&e50[i]-c[i].close<=maxExt;return buy?'BUY':sell?'SELL':null}
function trade(c,i,side,a){const j=i+1;if(j>=c.length)return null;const e=side==='BUY'?c[j].open+SLIP:c[j].open-SLIP,risk=1.2*a,baseSL=side==='BUY'?e-risk:e+risk,tp=side==='BUY'?e+2*risk:e-2*risk,cost=(SPREAD+2*SLIP)/risk;let sl=baseSL,end=Math.min(c.length-1,j+36);for(let k=j;k<=end;k++){const b=c[k];const rr=side==='BUY'?(b.close-e)/risk:(e-b.close)/risk;if(rr>=1)sl=side==='BUY'?Math.max(sl,e):Math.min(sl,e);const hitSL=side==='BUY'?b.low<=sl:b.high>=sl,hitTP=side==='BUY'?b.high>=tp:b.low<=tp;if(hitSL&&hitTP)return{side,exit:k,r:(sl===e?0:-1)-cost,reason:'BOTH'};if(hitSL)return{side,exit:k,r:(sl===e?0:-1)-cost,reason:sl===e?'BE':'SL'};if(hitTP)return{side,exit:k,r:2-cost,reason:'TP'};if(k>=j+6&&rr<-.35)return{side,exit:k,r:rr-cost,reason:'WEAK'};if(k>=j+24&&Math.abs(rr)<.25)return{side,exit:k,r:rr-cost,reason:'STAG'}}const px=c[end].close,rr=side==='BUY'?(px-e)/risk:(e-px)/risk;return{side,exit:end,r:rr-cost,reason:'TIME'}}
function run(c,from,to){const cl=c.map(x=>x.close),e50=ema(cl,50),a=atr(c,14),out=[];let free=from;for(let i=Math.max(from,60);i<Math.min(to,c.length-2);i++){if(i<free)continue;const side=signal(c,i,e50,a);if(!side)continue;const t=trade(c,i,side,a[i]);if(t){out.push(t);free=t.exit+1}}return out}
function yearly(c,t){const m={};for(const x of t){const y=new Date(c[x.exit].time).getUTCFullYear();(m[y]??=[]).push(x)}return m}
(async()=>{console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n⚡ GOLD BREAKOUT PRO — REBUILD\nXAUUSD H4 | Dukascopy-derived H4\nDonchian20 breakout + EMA50 direction + ATR distance control\nSL 1.2 ATR | TP 2R | BE at 1R | weak/stagnation exits\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');const raw=await getGoldHistoricalCandles('5min',H),m5=raw.map(r=>({time:+(r.time??r.timestamp),open:+r.open,high:+r.high,low:+r.low,close:+r.close})).filter(r=>[r.time,r.open,r.high,r.low,r.close].every(Number.isFinite)).sort((a,b)=>a.time-b.time),c=agg(m5,240);console.log(`✅ H4 candles built: ${c.length}`);let s=60,u=c.length-s,de=s+Math.floor(u*.6),ve=s+Math.floor(u*.8),D=run(c,s,de),V=run(c,de,ve),O=run(c,ve,c.length),F=run(c,s,c.length);console.log('\n📊 DEV\n'+fmt(stats(D)));console.log('\n📊 VAL\n'+fmt(stats(V)));console.log('\n🧪 OOS — UNTOUCHED 20%\n'+fmt(stats(O)));console.log('\n📈 OOS BUY\n'+fmt(stats(O.filter(x=>x.side==='BUY'))));console.log('\n📉 OOS SELL\n'+fmt(stats(O.filter(x=>x.side==='SELL'))));console.log('\n📅 YEARLY — FULL HISTORY');for(const [y,t] of Object.entries(yearly(c,F)))console.log(`${y} | ${fmt(stats(t))}`);const file=path.join(OUT,'gold-breakout-pro-rebuild-dukascopy.json');fs.writeFileSync(file,JSON.stringify({note:'Approximate rebuild from protected published description; not original source code.',dev:stats(D),val:stats(V),oos:stats(O),full:stats(F)},null,2));console.log(`\n💾 ${file}`)})().catch(e=>{console.error(e);process.exit(1)});