const { getGoldHistoricalCandles } = require('./backtestHistoryDukascopyLocal');
const COST=Number(process.env.COST_PRICE||0.45),RR=1.5,YEAR_MS=365.25*24*60*60*1000;
function agg(c,m){const o=[];for(let i=0;i+m<=c.length;i+=m){const z=c.slice(i,i+m);o.push({time:z[0].time,open:z[0].open,high:Math.max(...z.map(x=>x.high)),low:Math.min(...z.map(x=>x.low)),close:z[m-1].close,volume:z.reduce((s,x)=>s+(x.volume||0),0),endIndex:i+m-1});}return o;}
function emaSeries(a,p){const o=Array(a.length).fill(null);if(a.length<p)return o;let e=0;for(let i=0;i<p;i++)e+=a[i];e/=p;o[p-1]=e;const k=2/(p+1);for(let i=p;i<a.length;i++){e=a[i]*k+e*(1-k);o[i]=e;}return o;}
function atrSeries(c,p=14){const o=Array(c.length).fill(null),tr=Array(c.length).fill(null);for(let i=1;i<c.length;i++)tr[i]=Math.max(c[i].high-c[i].low,Math.abs(c[i].high-c[i-1].close),Math.abs(c[i].low-c[i-1].close));for(let i=p;i<c.length;i++){let s=0;for(let j=i-p+1;j<=i;j++)s+=tr[j];o[i]=s/p;}return o;}
function rsiSeries(a,p=14){const o=Array(a.length).fill(null);for(let i=p;i<a.length;i++){let g=0,l=0;for(let j=i-p+1;j<=i;j++){const d=a[j]-a[j-1];d>=0?g+=d:l-=d;}o[i]=l===0?100:100-100/(1+g/l);}return o;}
function adxSeries(c,p=14){const o=Array(c.length).fill(null),tr=[],pd=[],md=[];for(let i=1;i<c.length;i++){const u=c[i].high-c[i-1].high,d=c[i-1].low-c[i].low;pd[i]=u>d&&u>0?u:0;md[i]=d>u&&d>0?d:0;tr[i]=Math.max(c[i].high-c[i].low,Math.abs(c[i].high-c[i-1].close),Math.abs(c[i].low-c[i-1].close));}const dx=Array(c.length).fill(null);for(let i=p;i<c.length;i++){let T=0,P=0,M=0;for(let j=i-p+1;j<=i;j++){T+=tr[j]||0;P+=pd[j]||0;M+=md[j]||0;}if(T){P=100*P/T;M=100*M/T;if(P+M)dx[i]=100*Math.abs(P-M)/(P+M);}}for(let i=p*2-1;i<c.length;i++){let s=0,k=0;for(let j=i-p+1;j<=i;j++)if(dx[j]!=null){s+=dx[j];k++;}if(k===p)o[i]=s/p;}return o;}
function vwap24(c){const o=Array(c.length).fill(null);for(let i=23;i<c.length;i++){let pv=0,v=0;for(let j=i-23;j<=i;j++){const q=c[j].volume||0;if(q>0){pv+=(c[j].high+c[j].low+c[j].close)/3*q;v+=q;}}o[i]=v?pv/v:null;}return o;}
function stats(t){if(!t.length)return{trades:0,wr:0,netR:0,avgR:0,pf:0,dd:0,ls:0};let w=0,gw=0,gl=0,e=0,pk=0,dd=0,ls=0,ml=0;for(const x of t){e+=x.r;if(x.r>0){w++;gw+=x.r;ls=0}else{gl-=x.r;ls++;ml=Math.max(ml,ls)}pk=Math.max(pk,e);dd=Math.max(dd,pk-e)}return{trades:t.length,wr:100*w/t.length,netR:e,avgR:e/t.length,pf:gl?gw/gl:999,dd,ls:ml};}
const f=s=>`${s.trades} trades | WR ${s.wr.toFixed(1)}% | Net ${s.netR>=0?'+':''}${s.netR.toFixed(2)}R | Avg ${s.avgR.toFixed(3)}R | PF ${s.pf.toFixed(2)} | DD ${s.dd.toFixed(2)}R | LS ${s.ls}`;
(async()=>{console.log('⚡ GOLD REGIME — FAST LAST-12-MONTH DUKASCOPY BACKTEST');let all=(await getGoldHistoricalCandles('5min',100000)).map(x=>({...x,time:+x.time,open:+x.open,high:+x.high,low:+x.low,close:+x.close,volume:+x.volume||0}));const end=all[all.length-1].time,start=end-YEAR_MS,warm=start-7*24*60*60*1000,c=all.filter(x=>x.time>=warm),first=c.findIndex(x=>x.time>=start);console.log(`📅 Period: ${new Date(start).toISOString().slice(0,10)} → ${new Date(end).toISOString().slice(0,10)} | ${c.length-first} M5 candles`);
const close=c.map(x=>x.close),e9=emaSeries(close,9),e20=emaSeries(close,20),A=atrSeries(c),R=rsiSeries(close),V=vwap24(c),m15=agg(c,3),h1=agg(c,12),m15c=m15.map(x=>x.close),h1c=h1.map(x=>x.close),m15e20=emaSeries(m15c,20),m15e50=emaSeries(m15c,50),h1e20=emaSeries(h1c,20),h1e50=emaSeries(h1c,50),a15=adxSeries(m15);let mi=0,hi=0,p=null,out=[];
for(let i=Math.max(first,100);i<c.length-1;i++){while(mi+1<m15.length&&m15[mi+1].endIndex<=i)mi++;while(hi+1<h1.length&&h1[hi+1].endIndex<=i)hi++;if(p){const hs=p.side==='BUY'?c[i].low<=p.sl:c[i].high>=p.sl,ht=p.side==='BUY'?c[i].high>=p.tp:c[i].low<=p.tp;if(hs||ht){out.push({...p,r:(hs?-1:RR)-COST/p.risk});p=null;}continue;}if(![e9[i],e20[i],A[i],R[i],V[i],m15e20[mi],m15e50[mi],h1e20[hi],h1e50[hi],a15[mi]].every(Number.isFinite))continue;const t15=m15e20[mi]>m15e50[mi]?'BUY':'SELL',t1=h1e20[hi]>h1e50[hi]?'BUY':'SELL';if(t15!==t1||a15[mi]<23)continue;const side=t15,entry=c[i+1].open;if(!(side==='BUY'?e9[i]>e20[i]:e9[i]<e20[i]))continue;if(!(side==='BUY'?entry>=V[i]-A[i]*.08:entry<=V[i]+A[i]*.08))continue;const anchor=Math.min(Math.abs(entry-e20[i]),Math.abs(entry-V[i]))/A[i];if(anchor>.55)continue;const rec=c.slice(i-2,i+1),tol=A[i]*.20,touch=rec.some(x=>x.low<=e20[i]+tol&&x.high>=e20[i]-tol)||rec.some(x=>x.low<=V[i]+tol&&x.high>=V[i]-tol);if(!touch)continue;const last=c[i],range=last.high-last.low,body=Math.abs(last.close-last.open);if(range/A[i]>1.2||body/A[i]>.8||body/Math.max(range,.00001)<.30)continue;const confirm=side==='BUY'?last.close>last.open&&(last.close>=e20[i]||last.close>=V[i]):last.close<last.open&&(last.close<=e20[i]||last.close<=V[i]);if(!confirm)continue;const z=c.slice(i-2,i+1),imp=z.reduce((s,x)=>s+x.close-x.open,0),str=Math.abs(z.reduce((s,x)=>s+(x.close>x.open?1:x.close<x.open?-1:0),0));if((imp>0?'BUY':imp<0?'SELL':null)!==side||str<2)continue;if(!(side==='BUY'?R[i]>=44&&R[i]<=70:R[i]>=30&&R[i]<=56))continue;const move=(entry-last.open)/A[i],trigger=side==='BUY'?move>=.02&&entry>=e20[i]:move<=-.02&&entry<=e20[i];if(!trigger||Math.abs(move)>.35)continue;const vals=c.slice(i-11,i+1).map(x=>side==='BUY'?x.low:x.high),sw=side==='BUY'?Math.min(...vals):Math.max(...vals),risk=Math.max(side==='BUY'?entry-sw:sw-entry,A[i]*.55);p={side,entry,risk,sl:side==='BUY'?entry-risk:entry+risk,tp:side==='BUY'?entry+RR*risk:entry-RR*risk,time:c[i+1].time};}
console.log('\n📊 LAST 12 MONTHS\n'+f(stats(out)));console.log('\n📈 BUY\n'+f(stats(out.filter(x=>x.side==='BUY')))+'\n\n📉 SELL\n'+f(stats(out.filter(x=>x.side==='SELL'))));const y={};for(const t of out)(y[new Date(t.time).getUTCFullYear()]??=[]).push(t);console.log('\n📅 YEAR SPLIT');for(const[k,v]of Object.entries(y))console.log(`${k} | ${f(stats(v))}`);})().catch(e=>{console.error(e);process.exit(1)});
