const { getHistoricalRates } = require('dukascopy-node');

const FROM = process.argv[2] || '2024-08-23';
const TO = process.argv[3] || '2026-08-23';

function tf(rows,min){const ms=min*60000,m=new Map();for(const x of rows){const t=Math.floor(x.timestamp/ms)*ms;if(!m.has(t))m.set(t,{timestamp:t,open:x.open,high:x.high,low:x.low,close:x.close,volume:x.volume||0});else{const b=m.get(t);b.high=Math.max(b.high,x.high);b.low=Math.min(b.low,x.low);b.close=x.close;b.volume+=(x.volume||0);}}return [...m.values()].sort((a,b)=>a.timestamp-b.timestamp);}
function prevIndex(rows,ts){let lo=0,hi=rows.length;while(lo<hi){const m=(lo+hi)>>1;if(rows[m].timestamp<ts)lo=m+1;else hi=m;}return lo-1;}
function emaSeries(v,p){const o=Array(v.length).fill(null),k=2/(p+1);if(!v.length)return o;let e=v[0];for(let i=0;i<v.length;i++){if(i>0)e=v[i]*k+e*(1-k);if(i>=p-1)o[i]=e;}return o;}
function rsiSeries(v,p=14){const o=Array(v.length).fill(null);let ag=null,al=null;for(let i=1;i<v.length;i++){const d=v[i]-v[i-1],g=Math.max(d,0),l=Math.max(-d,0);if(i===p){let gs=0,ls=0;for(let j=1;j<=p;j++){const x=v[j]-v[j-1];gs+=Math.max(x,0);ls+=Math.max(-x,0);}ag=gs/p;al=ls/p;}else if(i>p){ag=(ag*(p-1)+g)/p;al=(al*(p-1)+l)/p;}if(i>=p)o[i]=al===0?100:100-100/(1+ag/al);}return o;}
function atrSeries(c,p=14){const o=Array(c.length).fill(null);for(let i=p;i<c.length;i++){let s=0;for(let j=i-p+1;j<=i;j++){const pc=c[j-1].close;s+=Math.max(c[j].high-c[j].low,Math.abs(c[j].high-pc),Math.abs(c[j].low-pc));}o[i]=s/p;}return o;}
function adxSeries(c,p=14){const o=Array(c.length).fill(null),tr=Array(c.length).fill(0),pd=Array(c.length).fill(0),md=Array(c.length).fill(0);for(let i=1;i<c.length;i++){const up=c[i].high-c[i-1].high,dn=c[i-1].low-c[i].low;pd[i]=up>dn&&up>0?up:0;md[i]=dn>up&&dn>0?dn:0;tr[i]=Math.max(c[i].high-c[i].low,Math.abs(c[i].high-c[i-1].close),Math.abs(c[i].low-c[i-1].close));}if(c.length<=p*2)return o;let trN=0,pN=0,mN=0;for(let i=1;i<=p;i++){trN+=tr[i];pN+=pd[i];mN+=md[i];}const dx=Array(c.length).fill(null);for(let i=p;i<c.length;i++){if(i>p){trN=trN-trN/p+tr[i];pN=pN-pN/p+pd[i];mN=mN-mN/p+md[i];}if(trN<=0)continue;const pdi=100*pN/trN,mdi=100*mN/trN,den=pdi+mdi;if(den>0)dx[i]=100*Math.abs(pdi-mdi)/den;}let seed=0,count=0;for(let i=p;i<c.length;i++){if(!Number.isFinite(dx[i]))continue;if(count<p){seed+=dx[i];count++;if(count===p)o[i]=seed/p;}else if(Number.isFinite(o[i-1]))o[i]=(o[i-1]*(p-1)+dx[i])/p;}return o;}
function vwapSeries(c,lookback=24){const o=Array(c.length).fill(null);let pv=0,vol=0;const q=[];for(let i=0;i<c.length;i++){const v=Number(c[i].volume)||0,tp=(c[i].high+c[i].low+c[i].close)/3;q.push([tp,v]);pv+=tp*v;vol+=v;if(q.length>lookback){const [otp,ov]=q.shift();pv-=otp*ov;vol-=ov;}o[i]=vol>0?pv/vol:null;}return o;}
function trendSeries(c){const cls=c.map(x=>x.close),e20=emaSeries(cls,20),e50=emaSeries(cls,50);return c.map((_,i)=>e20[i]>e50[i]?'BUY':e20[i]<e50[i]?'SELL':null);}
function simFixed(m5,start,side,entry,sl,tp,maxBars=4320){for(let j=start;j<m5.length&&j<=start+maxBars;j++){const b=m5[j];if(side==='BUY'){if(b.low<=sl)return{r:-1,exit:j};if(b.high>=tp)return{r:(tp-entry)/(entry-sl),exit:j};}else{if(b.high>=sl)return{r:-1,exit:j};if(b.low<=tp)return{r:(entry-tp)/(sl-entry),exit:j};}}return null;}
function stats(name,trades){let net=0,peak=0,dd=0,gp=0,gl=0,w=0,ls=0,maxLs=0;const years={};for(const t of trades){net+=t.r;if(t.r>0){w++;gp+=t.r;ls=0;}else{gl+=Math.abs(t.r);ls++;maxLs=Math.max(maxLs,ls);}peak=Math.max(peak,net);dd=Math.max(dd,peak-net);const y=new Date(t.time).getUTCFullYear();if(!years[y])years[y]={n:0,r:0};years[y].n++;years[y].r+=t.r;}return{name,trades:trades.length,wr:trades.length?w/trades.length*100:0,net,avg:trades.length?net/trades.length:0,pf:gl?gp/gl:(gp>0?999:0),dd,maxLs,years};}
function print(s){console.log('\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');console.log(`📊 ${s.name}`);console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');console.log(`Trades: ${s.trades}`);console.log(`WR: ${s.wr.toFixed(1)}%`);console.log(`Net R: ${s.net>=0?'+':''}${s.net.toFixed(2)}R`);console.log(`Avg R: ${s.avg.toFixed(3)}R`);console.log(`PF: ${Number.isFinite(s.pf)?s.pf.toFixed(2):'∞'}`);console.log(`DD: ${s.dd.toFixed(2)}R`);console.log(`Max LS: ${s.maxLs}`);console.log('\n📅 Yearly');for(const [y,v] of Object.entries(s.years))console.log(`${y} | ${v.n} | ${v.r>=0?'+':''}${v.r.toFixed(2)}R`);}

const TZ=new Map();
function localMinutes(ts,tz){let f=TZ.get(tz);if(!f){f=new Intl.DateTimeFormat('en-US',{timeZone:tz,hour12:false,hour:'2-digit',minute:'2-digit'});TZ.set(tz,f);}const p=f.formatToParts(new Date(ts));const h=Number(p.find(x=>x.type==='hour')?.value||0),m=Number(p.find(x=>x.type==='minute')?.value||0);return h*60+m;}
function sessionAllowed(ts,mode){if(mode==='ALL')return true;if(mode==='LONDON'){const m=localMinutes(ts,'Europe/London');return m>=8*60&&m<12*60;}if(mode==='NY'){const m=localMinutes(ts,'America/New_York');return m>=8*60+30&&m<12*60;}return false;}
function sideAllowed(side,mode){return mode==='BOTH'||mode===side;}

function runRegime(m5,m15,h1,ind,cfg,startIndex,endIndex){const out=[];for(let i=Math.max(100,startIndex);i<Math.min(endIndex,m5.length-2);i++){const eidx=i+1;if(!sessionAllowed(m5[eidx].timestamp,cfg.session))continue;const j15=prevIndex(m15,m5[i].timestamp+1),j1=prevIndex(h1,m5[i].timestamp+1);if(j15<55||j1<55)continue;const t15=ind.t15[j15],t1=ind.t1[j1];if(!t15||t15!==t1||!(ind.adx15[j15]>=cfg.adxMin)||!sideAllowed(t15,cfg.side))continue;const side=t15,atr=ind.a5[i];if(!(atr>0))continue;if(side==='BUY'&&!(ind.e9[i]>ind.e20[i]))continue;if(side==='SELL'&&!(ind.e9[i]<ind.e20[i]))continue;const entryOpen=m5[eidx].open;if(side==='BUY'&&entryOpen<ind.vw[i]-atr*0.08)continue;if(side==='SELL'&&entryOpen>ind.vw[i]+atr*0.08)continue;const anchor=Math.min(Math.abs(entryOpen-ind.e20[i]),Math.abs(entryOpen-ind.vw[i]))/atr;if(anchor>cfg.anchorMax||Math.abs(entryOpen-ind.e20[i])/atr>cfg.anchorMax)continue;const recent=m5.slice(i-2,i+1),tol=atr*0.20;const touched=recent.some(x=>(x.high>=ind.e20[i]-tol&&x.low<=ind.e20[i]+tol)||(x.high>=ind.vw[i]-tol&&x.low<=ind.vw[i]+tol));if(!touched)continue;const b=m5[i],range=Math.max(b.high-b.low,1e-9),body=Math.abs(b.close-b.open),upper=b.high-Math.max(b.open,b.close),lower=Math.min(b.open,b.close)-b.low;if(range/atr>1.2||body/atr>0.8)continue;const dirClose=side==='BUY'?b.close>b.open:b.close<b.open,closeBack=side==='BUY'?(b.close>=ind.e20[i]||b.close>=ind.vw[i]):(b.close<=ind.e20[i]||b.close<=ind.vw[i]),rej=side==='BUY'?(lower>=upper*1.15&&lower>=body*0.35):(upper>=lower*1.15&&upper>=body*0.35),cont=dirClose&&body/range>=cfg.bodyShareMin;if(!(dirClose&&closeBack&&(rej||cont)))continue;let up=0,dn=0;for(let k=i-3;k<=i;k++){if(k<=0)continue;if(m5[k].close>m5[k-1].close)up++;else if(m5[k].close<m5[k-1].close)dn++;}const md=up>=3?'BUY':dn>=3?'SELL':up>dn?'BUY':dn>up?'SELL':'WAIT',strength=Math.max(up,dn);if(md!==side||strength<2)continue;const rr=ind.r5[i];if(side==='BUY'&&!(rr>=44&&rr<=70))continue;if(side==='SELL'&&!(rr<=56&&rr>=30))continue;const liveMove=(m5[eidx].close-m5[eidx].open)/atr;if(side==='BUY'&&!(liveMove>=0.02&&m5[eidx].close>=ind.e20[i]))continue;if(side==='SELL'&&!(liveMove<=-0.02&&m5[eidx].close<=ind.e20[i]))continue;if(Math.abs(liveMove)>0.35)continue;const liveEntry=m5[eidx].close,swingRows=m5.slice(Math.max(0,i-11),i+1),swing=side==='BUY'?Math.min(...swingRows.map(x=>x.low)):Math.max(...swingRows.map(x=>x.high)),base=Math.max(atr*1.2,3),swingRisk=side==='BUY'?liveEntry-swing+Math.max(atr*0.15,0.5):swing-liveEntry+Math.max(atr*0.15,0.5),risk=Math.min(Math.max(base,swingRisk>0?swingRisk:base),Math.max(atr*2.2,8.5));const sl=side==='BUY'?liveEntry-risk:liveEntry+risk,tp=side==='BUY'?liveEntry+risk*cfg.tpR:liveEntry-risk*cfg.tpR;const z=simFixed(m5,eidx,side,liveEntry,sl,tp);if(!z)continue;out.push({time:m5[eidx].timestamp,r:z.r,side});i=z.exit;}return out;}

function devScore(s){if(s.trades<20)return -999;return s.net*1.2+s.avg*20+Math.log10(Math.max(.1,Math.min(3,s.pf)))*12-s.dd;}
function robustScore(dev,val,hold,full){if(val.trades<5||hold.trades<5||full.trades<35)return -9999;let score=0;score+=Math.min(dev.net,val.net*2,hold.net*2)*3;score+=val.net*2.5+hold.net*2.5+full.net*0.6;score+=Math.min(val.pf,3)*5+Math.min(hold.pf,3)*5+Math.min(full.pf,3)*3;score-=full.dd*1.4+Math.max(0,-val.net)*5+Math.max(0,-hold.net)*5;const yr=Object.values(full.years);const neg=yr.filter(x=>x.r<0).length;score-=neg*8;return score;}

(async()=>{
  console.log('🧭 GOLD REGIME — DUKASCOPY ROBUST OPTIMIZER V2');
  console.log(`📅 ${FROM} → ${TO}`);
  console.log('⏳ Loading XAUUSD M5 from Dukascopy...');
  const raw=await getHistoricalRates({instrument:'xauusd',dates:{from:new Date(FROM+'T00:00:00Z'),to:new Date(TO+'T23:59:59Z')},timeframe:'m5',format:'json',volumes:true,batchSize:10,pauseBetweenBatchesMs:500,useCache:true,cacheFolderPath:'./data/dukascopy-cache'});
  const m5=raw.map(x=>({timestamp:+x.timestamp,open:+x.open,high:+x.high,low:+x.low,close:+x.close,volume:+x.volume||0})).filter(x=>[x.timestamp,x.open,x.high,x.low,x.close].every(Number.isFinite)).sort((a,b)=>a.timestamp-b.timestamp);
  const m15=tf(m5,15),h1=tf(m5,60);console.log(`✅ M5 ${m5.length} | M15 ${m15.length} | H1 ${h1.length}`);
  const cls=m5.map(x=>x.close),ind={e9:emaSeries(cls,9),e20:emaSeries(cls,20),r5:rsiSeries(cls,14),a5:atrSeries(m5,14),vw:vwapSeries(m5,24),adx15:adxSeries(m15,14),t15:trendSeries(m15),t1:trendSeries(h1)};
  const n=m5.length,devEnd=Math.floor(n*.60),valEnd=Math.floor(n*.80);
  const configs=[];
  for(const session of ['ALL','LONDON','NY'])for(const side of ['BOTH','BUY','SELL'])for(const adxMin of [23,26,29,32])for(const anchorMax of [.40,.55])for(const bodyShareMin of [.30,.40])for(const tpR of [1.2,1.5,1.8])configs.push({session,side,adxMin,anchorMax,bodyShareMin,tpR});
  console.log(`🔬 Stage 1 variants=${configs.length}`);
  const stage1=[];for(const cfg of configs){const dev=stats('DEV',runRegime(m5,m15,h1,ind,cfg,0,devEnd));stage1.push({cfg,dev,score:devScore(dev)});}stage1.sort((a,b)=>b.score-a.score);
  const finalists=stage1.slice(0,80);console.log(`🧪 Stage 2 finalists=${finalists.length}`);
  const ranked=[];for(const x of finalists){const val=stats('VAL',runRegime(m5,m15,h1,ind,x.cfg,devEnd,valEnd));const hold=stats('HOLDOUT',runRegime(m5,m15,h1,ind,x.cfg,valEnd,n-2));const full=stats('FULL',runRegime(m5,m15,h1,ind,x.cfg,0,n-2));ranked.push({...x,val,hold,full,robust:robustScore(x.dev,val,hold,full)});}ranked.sort((a,b)=>b.robust-a.robust);
  console.log('\n🏆 TOP 10 ROBUST CONFIGS');console.table(ranked.slice(0,10).map((x,i)=>({Rank:i+1,...x.cfg,DEV:x.dev.net.toFixed(1),VAL:x.val.net.toFixed(1),HOLD:x.hold.net.toFixed(1),FULL:x.full.net.toFixed(1),PF:x.full.pf.toFixed(2),DD:x.full.dd.toFixed(1),Trades:x.full.trades,Score:x.robust.toFixed(1)})));
  for(let i=0;i<Math.min(5,ranked.length);i++){console.log(`\n🥇 Candidate ${i+1}: ${JSON.stringify(ranked[i].cfg)}`);print(ranked[i].dev);print(ranked[i].val);print(ranked[i].hold);print(ranked[i].full);}
})().catch(e=>{console.error('❌ OPTIMIZER ERROR:',e);process.exit(1);});