const { getGoldHistoricalCandles } = require('./backtestHistoryDukascopyLocal');
const HISTORY=Math.max(30000,Math.min(141000,Number(process.env.BACKTEST_HISTORY||100000)));
const ADX_MIN=20, RSI_BUY=60, RSI_SELL=40, RSI_PERIOD=8, ATR_MULT=1, COST_R=.03;
function agg(c,f){const o=[];for(let i=0;i+f<=c.length;i+=f){const z=c.slice(i,i+f);o.push({time:+z[0].time,open:+z[0].open,high:Math.max(...z.map(x=>+x.high)),low:Math.min(...z.map(x=>+x.low)),close:+z[z.length-1].close})}return o}
function ema(v,p){const o=Array(v.length).fill(null);let e=v[0],k=2/(p+1);for(let i=0;i<v.length;i++){if(i)e=v[i]*k+e*(1-k);if(i>=p-1)o[i]=e}return o}
function atr(c,p=14){const o=Array(c.length).fill(null),tr=Array(c.length).fill(null);for(let i=1;i<c.length;i++)tr[i]=Math.max(c[i].high-c[i].low,Math.abs(c[i].high-c[i-1].close),Math.abs(c[i].low-c[i-1].close));for(let i=p;i<c.length;i++){let s=0;for(let j=i-p+1;j<=i;j++)s+=tr[j];o[i]=s/p}return o}
function rsi(v,p=14){const o=Array(v.length).fill(null);let ag,al;for(let i=1;i<v.length;i++){const d=v[i]-v[i-1],g=Math.max(d,0),l=Math.max(-d,0);if(i===p){let G=0,L=0;for(let j=1;j<=p;j++){const q=v[j]-v[j-1];G+=Math.max(q,0);L+=Math.max(-q,0)}ag=G/p;al=L/p}else if(i>p){ag=(ag*(p-1)+g)/p;al=(al*(p-1)+l)/p}if(i>=p)o[i]=al===0?100:100-100/(1+ag/al)}return o}
function adx(c,p=14){const o=Array(c.length).fill(null),tr=Array(c.length).fill(0),pd=Array(c.length).fill(0),md=Array(c.length).fill(0),dx=Array(c.length).fill(null);for(let i=1;i<c.length;i++){const u=c[i].high-c[i-1].high,d=c[i-1].low-c[i].low;pd[i]=u>d&&u>0?u:0;md[i]=d>u&&d>0?d:0;tr[i]=Math.max(c[i].high-c[i].low,Math.abs(c[i].high-c[i-1].close),Math.abs(c[i].low-c[i-1].close))}for(let i=p;i<c.length;i++){let T=0,P=0,M=0;for(let j=i-p+1;j<=i;j++){T+=tr[j];P+=pd[j];M+=md[j]}if(T){P=100*P/T;M=100*M/T;if(P+M)dx[i]=100*Math.abs(P-M)/(P+M)}}for(let i=2*p-1;i<c.length;i++){let s=0,n=0;for(let j=i-p+1;j<=i;j++)if(Number.isFinite(dx[j])){s+=dx[j];n++}if(n===p)o[i]=s/p}return o}
function stats(t){if(!t.length)return{trades:0,wr:0,netR:0,avgR:0,pf:0,dd:0,ls:0};let w=0,gp=0,gl=0,e=0,pk=0,dd=0,ls=0,ml=0;for(const x of t){e+=x.r;if(x.r>0){w++;gp+=x.r;ls=0}else{gl-=x.r;ls++;ml=Math.max(ml,ls)}pk=Math.max(pk,e);dd=Math.max(dd,pk-e)}return{trades:t.length,wr:100*w/t.length,netR:e,avgR:e/t.length,pf:gl?gp/gl:999,dd,ls:ml}}
const fmt=s=>`${s.trades} trades | WR ${s.wr.toFixed(1)}% | Net ${s.netR>=0?'+':''}${s.netR.toFixed(2)}R | Avg ${s.avgR.toFixed(3)}R | PF ${s.pf.toFixed(2)} | DD ${s.dd.toFixed(2)}R | LS ${s.ls}`;
function run(c,start,end,rr){const C=c.map(x=>x.close),E50=ema(C,50),R=rsi(C,RSI_PERIOD),A=atr(c),D=adx(c),out=[];let p=null;for(let i=Math.max(start,60);i<Math.min(end,c.length-1);i++){if(p){const b=c[i],sl=p.side==='BUY'?b.low<=p.sl:b.high>=p.sl,tp=p.side==='BUY'?b.high>=p.tp:b.low<=p.tp;if(sl||tp){out.push({...p,exitTime:b.time,r:(sl?-1:rr)-COST_R});p=null}continue}if(![E50[i],R[i],A[i],D[i]].every(Number.isFinite)||D[i]<ADX_MIN)continue;const b=c[i];let side=null;if(R[i]>=RSI_BUY&&b.close>E50[i]&&b.close>b.open)side='BUY';else if(R[i]<=RSI_SELL&&b.close<E50[i]&&b.close<b.open)side='SELL';if(!side)continue;const entry=c[i+1].open,risk=A[i]*ATR_MULT;p={side,time:c[i+1].time,entry,risk,sl:side==='BUY'?entry-risk:entry+risk,tp:side==='BUY'?entry+risk*rr:entry-risk*rr}}
return out}
(async()=>{console.log('⚡ GOLD RSI(8) + ADX + EMA50 — M15');console.log('BUY: RSI(8)>=60 + ADX>=20 + bullish candle closes above EMA50 | SELL: RSI(8)<=40 + ADX>=20 + bearish candle closes below EMA50 | entry next candle | SL=1ATR');const m5=(await getGoldHistoricalCandles('5min',HISTORY)).map(x=>({...x,time:+x.time,open:+x.open,high:+x.high,low:+x.low,close:+x.close})),m15=agg(m5,3);console.log(`✅ Dukascopy local history: 5min ${m5.length} candles | M15 ${m15.length}`);const s=60,u=m15.length-s,de=s+Math.floor(u*.6),ve=s+Math.floor(u*.8);for(const rr of [1,1.25]){const D=run(m15,s,de,rr),V=run(m15,de,ve,rr),O=run(m15,ve,m15.length,rr),F=run(m15,s,m15.length,rr);console.log(`\n━━━━━━━━━━ TP ${rr}R ━━━━━━━━━━`);console.log('\n📊 DEV\n'+fmt(stats(D))+'\n\n📊 VAL\n'+fmt(stats(V))+'\n\n🧪 OOS — UNTOUCHED 20%\n'+fmt(stats(O)));console.log('\n📈 OOS BUY\n'+fmt(stats(O.filter(x=>x.side==='BUY')))+'\n\n📉 OOS SELL\n'+fmt(stats(O.filter(x=>x.side==='SELL'))));console.log('\n📅 YEARLY — FULL HISTORY');const y={};for(const t of F)(y[new Date(t.time).getUTCFullYear()]??=[]).push(t);for(const[k,v]of Object.entries(y))console.log(`${k} | ${fmt(stats(v))}`)}})().catch(e=>{console.error(e);process.exit(1)});
