const fs=require('fs'),path=require('path');
const base=path.join(__dirname,'backtestNewYorkDukascopyQuick.js');let s=fs.readFileSync(base,'utf8');
s=s.replace("const { getHistoricalRates } = require('dukascopy-node');","");
const old="const raw=await getHistoricalRates({instrument:'xauusd',dates:{from:new Date(FROM+'T00:00:00Z'),to:new Date(TO+'T23:59:59Z')},timeframe:'m5',format:'json',volumes:true,batchSize:10,pauseBetweenBatchesMs:500,useCache:true,cacheFolderPath:'./data/dukascopy-cache'});";
const neu="const all=JSON.parse(fs.readFileSync(path.join(__dirname,'../data/xauusd-m5-dukascopy.json'),'utf8')); const a=Date.parse(FROM+'T00:00:00Z'),b=Date.parse(TO+'T23:59:59Z'); const raw=all.filter(x=>+x.timestamp>=a&&+x.timestamp<=b);";
if(!s.includes(old))throw new Error('loader block not found');s=s.replace(old,neu);
s=s.replace("console.log('🗽 NEW YORK — DUKASCOPY QUICK OPTIMIZER');","console.log('⚡ NEW YORK — FAST LOCAL (3 VARIANTS)');");
s=s.replace("console.log('⏳ Loading XAUUSD M5 from Dukascopy...');","console.log('⚡ Reading local XAUUSD M5...');");
const cfgOld="const configs=[];for(const adxMin of [22,25])for(const chaseMax of [0.35,0.50])for(const rr of [1.0,1.25])configs.push({adxMin,chaseMax,rr,bodyMax:0.35});";
const cfgNew="const configs=[{adxMin:25,chaseMax:0.35,rr:1.0,bodyMax:0.35},{adxMin:25,chaseMax:0.35,rr:1.25,bodyMax:0.35},{adxMin:25,chaseMax:0.50,rr:1.25,bodyMax:0.35}];";
if(!s.includes(cfgOld))throw new Error('config block not found');s=s.replace(cfgOld,cfgNew);
eval(s);
