require('dotenv').config();
const fs=require('fs'),path=require('path');
const {getGoldHistoricalCandles}=require('./backtestHistoryDukascopyLocal');
const HISTORY=Math.max(10000,Math.min(100000,Number(process.env.BACKTEST_HISTORY||100000)));
const SPREAD=Math.max(0,Number(process.env.BACKTEST_SPREAD_USD||.35)),SLIP=Math.max(0,Number(process.env.BACKTEST_SLIPPAGE_USD||.05));
const OUT=path.resolve(process.cwd(),'data','backtests');fs.mkdirSync(OUT,{recursive:true});
const TP=[.7,1,1.5,2],LOOK=[6,12,18],ADX=[20,24,28],BODY=[.15,.3],WICK=[1.5,2],SWEEP=[.03,.08],SESS=['LDN_NY','NY'];
const ema=(v,p)=>{let o=Array(v.length).fill(null);if(v.length<p)return o;let s=0;for(let i=0;i<p;i++)s+=v[i];let e=s/p;o[p-1]=e;let k=2/(p+1);for(let i=p;i<v.length;i++){e=v[i]*k+e*(1-k);o[i]=e}return o};
function atr(c,p=14){let t=Array(c.length).fill(0),o=Array(c.length).fill(null);for(let i=1;i<c.length;i++)t[i]=Math.max(c[i].high-c[i].low,Math.abs(c[i].high-c[i-1].close),Math.abs(c[i].low-c[i-1].close));let s=0;for(let i=1;i<=p;i++)s+=t[i];let a=s/p;o[p]=a;for(let i=p+1;i<c.length;i++){a=(a*(p-1)+t[i])/p;o[i]=a}return o}
function adx(c,p=14){let o=Array(c.length).fill(null),tr=Array(c.length).fill(0),pd=Array(c.length).fill(0),md=Array(c.length).fill(0);for(let i=1;i<c.length;i++){let u=c[i].high-c[i-1].high,d=c[i-1].low-c[i].low;pd[i]=u>d&&u>0?u:0;md[i]=d>u&&d>0?d:0;tr[i]=Math.max(c[i].high-c[i].low,Math.abs(c[i].high-c[i-1].close),Math.abs(c[i].low-c[i-1].close))}let st=0,sp=0,sm=0;for(let i=1;i<=p;i++){st+=tr[i];sp+=pd[i];sm+=md[i]}let dx=Array(c.length).fill(null);for(let i=p;i<c.length;i++){if(i>p){st=st-st/p+tr[i];sp=sp-sp/p+pd[i];sm=sm-sm/p+md[i]}let pi=st?100*sp/st:0,mi=st?100*sm/st:0;dx[i]=pi+mi?100*Math.abs(pi-mi)/(pi+mi):0}let f=p*2-1,s=0;for(let i=p;i<=f;i++)s+=dx[i]||0;let a=s/p;o[f]=a;for(let i=f+1;i<c.length;i++){a=(a*(p-1)+(dx[i]||0))/p;o[i]=a}return o}
function agg(c,m=15){let z=m*60000,o=[],x;for(const r of c){let b=Math.floor(r.time/z)*z;if(!x||x.time!==b){if(x)o.push(x);x={time:b,open:r.open,high:r.high,low:r.low,close:r.close}}else{x.high=Math.max(x.high,r.high);x.low=Math.min(x.low,r.low);x.close=r.close}}if(x)o.push(x);return o}
function mapHTF(b,h,v,m=15){let o=Array(b.length).fill(null),j=-1,d=m*60000;for(let i=0;i<b.length;i++){while(j+1<h.length&&h[j+1].time+d<=b[i].time)j++;if(j>=0&&Number.isFinite(v[j]))o[i]=v[j]}return o}
const fmts={};function minute(t,z){fmts[z]??=new Intl.DateTimeFormat('en-GB',{timeZone:z,hour:'2-digit',minute:'2-digit',hourCycle:'h23'});let q={};for(const p of fmts[z].formatToParts(new Date(t)))q[p.type]=p.value;return +q.hour*60+(+q.minute)}
function sess(t,s){let l=minute(t,'Europe/London'),n=minute(t,'America/New_York'),L=l>=480&&l<720,N=n>=510&&n<720;return s==='NY'?N:L||N}
function signal(c,i,x,p){if(i<p.look+2||![x.a[i],x.d[i],x.e9[i],x.e21[i],x.h[i]].every(Number.isFinite)||x.d[i]<p.adx||!sess(c[i].time,p.sess))return null;let a=x.a[i],body=Math.abs(c[i].close-c[i].open);if(body/a<p.body)return null;let lo=Infinity,hi=-Infinity;for(let k=i-p.look;k<i;k++){lo=Math.min(lo,c[k].low);hi=Math.max(hi,c[k].high)}let sw=a*p.sweep,lw=Math.min(c[i].open,c[i].close)-c[i].low,uw=c[i].high-Math.max(c[i].open,c[i].close);let B=c[i].close>x.h[i]&&x.e9[i]>x.e21[i]&&c[i].low<=lo-sw&&c[i].close>lo&&c[i].close>c[i].open&&lw>=Math.max(body*p.wick,a*.1);let S=c[i].close<x.h[i]&&x.e9[i]<x.e21[i]&&c[i].high>=hi+sw&&c[i].close<hi&&c[i].close<c[i].open&&uw>=Math.max(body*p.wick,a*.1);return B?'BUY':S?'SELL':null}
function trade(c,i,side,a,tp){let j=i+1,e=side==='BUY'?c[j].open+SLIP:c[j].open-SLIP,r=side==='BUY'?e-(c[i].low-a*.05):(c[i].high+a*.05)-e;r=Math.max(r,a*.35);if(r>a*1.5||r<=0)return null;let sl=side==='BUY'?e-r:e+r,T=side==='BUY'?e+r*tp:e-r*tp,cost=(SPREAD+2*SLIP)/r,end=Math.min(c.length-1,j+24);for(let k=j;k<=end;k++){let hs=side==='BUY'?c[k].low<=sl:c[k].high>=sl,ht=side==='BUY'?c[k].high>=T:c[k].low<=T;if(hs)return{side,exit:k,r:-1-cost};if(ht)return{side,exit:k,r:tp-cost}}let q=side==='BUY'?(c[end].close-e)/r:(e-c[end].close)/r;return{side,exit:end,r:q-cost}}
function run(c,x,p,a,b){let o=[],free=a;for(let i=Math.max(a,250);i<Math.min(b,c.length-2);i++){if(i<free)continue;let s=signal(c,i,x,p);if(!s)continue;let t=trade(c,i,s,x.a[i],p.tp);if(t){o.push(t);free=t.exit+1}}return o}
function stats(t){if(!t.length)return{trades:0,wr:0,netR:0,avgR:0,pf:0,dd:0,maxLS:0};let w=0,gw=0,gl=0,e=0,pk=0,dd=0,ls=0,ml=0;for(const x of t){e+=x.r;if(x.r>0){w++;gw+=x.r;ls=0}else{gl+=Math.abs(x.r);ls++;ml=Math.max(ml,ls)}pk=Math.max(pk,e);dd=Math.max(dd,pk-e)}return{trades:t.length,wr:w/t.length*100,netR:e,avgR:e/t.length,pf:gl?gw/gl:999,dd,maxLS:ml}}
const fmt=s=>`${s.trades} trades | WR ${s.wr.toFixed(1)}% | Net ${s.netR>=0?'+':''}${s.netR.toFixed(2)}R | Avg ${s.avgR.toFixed(3)}R | PF ${s.pf.toFixed(2)} | DD ${s.dd.toFixed(2)}R | LS ${s.maxLS}`;
const score=(d,v)=>d.trades<30||v.trades<10||v.netR<=0||v.pf<1?-1e9:Math.min(d.pf,v.pf)*2+Math.min(d.avgR,v.avgR)*4+Math.min(d.wr,v.wr)/100-(d.dd+v.dd)*.025;
(async()=>{console.log('⚡ LIQUIDITY SWEEP SCALPER — DUKASCOPY');let raw=await getGoldHistoricalCandles('5min',HISTORY),c=raw.map(r=>({time:+(r.time??r.timestamp),open:+r.open,high:+r.high,low:+r.low,close:+r.close})).filter(r=>[r.time,r.open,r.high,r.low,r.close].every(Number.isFinite));let h15=agg(c),he=ema(h15.map(z=>z.close),200),x={e9:ema(c.map(z=>z.close),9),e21:ema(c.map(z=>z.close),21),a:atr(c),d:adx(c),h:mapHTF(c,h15,he)};let st=250;while(st<c.length&&!Number.isFinite(x.h[st]))st++;let u=c.length-st,de=st+Math.floor(u*.6),ve=st+Math.floor(u*.8),vars=[];for(const tp of TP)for(const look of LOOK)for(const adx of ADX)for(const body of BODY)for(const wick of WICK)for(const sweep of SWEEP)for(const sess of SESS)vars.push({tp,look,adx,body,wick,sweep,sess});console.log(`🔬 Variants=${vars.length}`);let b=[];for(let i=0;i<vars.length;i++){let p=vars[i],d=stats(run(c,x,p,st,de)),v=stats(run(c,x,p,de,ve));b.push({p,d,v,s:score(d,v)});if((i+1)%100===0||i===vars.length-1)console.log(`🔍 ${i+1}/${vars.length}`)}b.sort((a,z)=>z.s-a.s);let top=b.filter(q=>q.s>-1e8).slice(0,10);console.log('\n🏆 TOP DEV+VAL');top.forEach((q,i)=>{console.log(`${i+1}. ${JSON.stringify(q.p)}\n   DEV ${fmt(q.d)}\n   VAL ${fmt(q.v)} | score=${q.s.toFixed(3)}`)});if(!top.length)return console.log('❌ No robust variant passed VAL');let best=top[0],ot=run(c,x,best.p,ve,c.length),o=stats(ot);console.log('\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n🧪 OOS — UNTOUCHED 20%\n'+`Params: ${JSON.stringify(best.p)}\n${fmt(o)}\n📈 BUY ${fmt(stats(ot.filter(t=>t.side==='BUY')))}\n📉 SELL ${fmt(stats(ot.filter(t=>t.side==='SELL')))}\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`);fs.writeFileSync(path.join(OUT,'liquidity-sweep-scalp-dukascopy.json'),JSON.stringify({best,oos:o},null,2))})().catch(e=>{console.error(e);process.exit(1)});