require('dotenv').config();
const fs=require('fs'),path=require('path');
const {getGoldHistoricalCandles}=require('./backtestHistoryDukascopyLocal');
const HISTORY=Math.max(10000,Math.min(100000,Number(process.env.BACKTEST_HISTORY||100000)));
const SPREAD=Math.max(0,Number(process.env.BACKTEST_SPREAD_USD||.35));
const SLIP=Math.max(0,Number(process.env.BACKTEST_SLIPPAGE_USD||.05));
const OUT=path.resolve(process.cwd(),'data','backtests');fs.mkdirSync(OUT,{recursive:true});
const P={tp:1.5,look:12,adx:24,body:.15,wick:1.5,sweep:.05,sess:'LDN_NY'};
const ema=(v,p)=>{let o=Array(v.length).fill(null);if(v.length<p)return o;let s=0;for(let i=0;i<p;i++)s+=v[i];let e=s/p;o[p-1]=e;let k=2/(p+1);for(let i=p;i<v.length;i++){e=v[i]*k+e*(1-k);o[i]=e}return o};
function atr(c,p=14){let t=Array(c.length).fill(0),o=Array(c.length).fill(null);for(let i=1;i<c.length;i++)t[i]=Math.max(c[i].high-c[i].low,Math.abs(c[i].high-c[i-1].close),Math.abs(c[i].low-c[i-1].close));let s=0;for(let i=1;i<=p;i++)s+=t[i];let a=s/p;o[p]=a;for(let i=p+1;i<c.length;i++){a=(a*(p-1)+t[i])/p;o[i]=a}return o}
function adx(c,p=14){let o=Array(c.length).fill(null),tr=Array(c.length).fill(0),pd=Array(c.length).fill(0),md=Array(c.length).fill(0);for(let i=1;i<c.length;i++){let u=c[i].high-c[i-1].high,d=c[i-1].low-c[i].low;pd[i]=u>d&&u>0?u:0;md[i]=d>u&&d>0?d:0;tr[i]=Math.max(c[i].high-c[i].low,Math.abs(c[i].high-c[i-1].close),Math.abs(c[i].low-c[i-1].close))}let st=0,sp=0,sm=0;for(let i=1;i<=p;i++){st+=tr[i];sp+=pd[i];sm+=md[i]}let dx=Array(c.length).fill(null);for(let i=p;i<c.length;i++){if(i>p){st=st-st/p+tr[i];sp=sp-sp/p+pd[i];sm=sm-sm/p+md[i]}let pi=st?100*sp/st:0,mi=st?100*sm/st:0;dx[i]=pi+mi?100*Math.abs(pi-mi)/(pi+mi):0}let f=p*2-1,s=0;for(let i=p;i<=f;i++)s+=dx[i]||0;let a=s/p;o[f]=a;for(let i=f+1;i<c.length;i++){a=(a*(p-1)+(dx[i]||0))/p;o[i]=a}return o}
function agg(c,m=15){let z=m*60000,o=[],x;for(const r of c){let b=Math.floor(r.time/z)*z;if(!x||x.time!==b){if(x)o.push(x);x={time:b,open:r.open,high:r.high,low:r.low,close:r.close}}else{x.high=Math.max(x.high,r.high);x.low=Math.min(x.low,r.low);x.close=r.close}}if(x)o.push(x);return o}
function mapHTF(b,h,v,m=15){let o=Array(b.length).fill(null),j=-1,d=m*60000;for(let i=0;i<b.length;i++){while(j+1<h.length&&h[j+1].time+d<=b[i].time)j++;if(j>=0&&Number.isFinite(v[j]))o[i]=v[j]}return o}
const fmts={};function minute(t,z){fmts[z]??=new Intl.DateTimeFormat('en-GB',{timeZone:z,hour:'2-digit',minute:'2-digit',hourCycle:'h23'});let q={};for(const p of fmts[z].formatToParts(new Date(t)))q[p.type]=p.value;return +q.hour*60+(+q.minute)}
function sess(t){let l=minute(t,'Europe/London'),n=minute(t,'America/New_York');return (l>=480&&l<720)||(n>=510&&n<720)}
function signal(c,i,x){if(i<P.look+2||![x.a[i],x.d[i],x.e9[i],x.e21[i],x.h[i]].every(Number.isFinite)||x.d[i]<P.adx||!sess(c[i].time))return null;let a=x.a[i],body=Math.abs(c[i].close-c[i].open);if(body/a<P.body)return null;let lo=Infinity,hi=-Infinity;for(let k=i-P.look;k<i;k++){lo=Math.min(lo,c[k].low);hi=Math.max(hi,c[k].high)}let sw=a*P.sweep,lw=Math.min(c[i].open,c[i].close)-c[i].low,uw=c[i].high-Math.max(c[i].open,c[i].close);let B=c[i].close>x.h[i]&&x.e9[i]>x.e21[i]&&c[i].low<=lo-sw&&c[i].close>lo&&c[i].close>c[i].open&&lw>=Math.max(body*P.wick,a*.1);let S=c[i].close<x.h[i]&&x.e9[i]<x.e21[i]&&c[i].high>=hi+sw&&c[i].close<hi&&c[i].close<c[i].open&&uw>=Math.max(body*P.wick,a*.1);return B?'BUY':S?'SELL':null}
function trade(c,i,side,a){let j=i+1,e=side==='BUY'?c[j].open+SLIP:c[j].open-SLIP,r=side==='BUY'?e-(c[i].low-a*.05):(c[i].high+a*.05)-e;r=Math.max(r,a*.35);if(r>a*1.5||r<=0)return null;let sl=side==='BUY'?e-r:e+r,tp=side==='BUY'?e+r*P.tp:e-r*P.tp,cost=(SPREAD+2*SLIP)/r,end=Math.min(c.length-1,j+24);for(let k=j;k<=end;k++){let hs=side==='BUY'?c[k].low<=sl:c[k].high>=sl,ht=side==='BUY'?c[k].high>=tp:c[k].low<=tp;if(hs&&ht)return{side,entryIndex:j,exit:k,time:c[j].time,r:-1-cost,reason:'BOTH->SL'};if(hs)return{side,entryIndex:j,exit:k,time:c[j].time,r:-1-cost,reason:'SL'};if(ht)return{side,entryIndex:j,exit:k,time:c[j].time,r:P.tp-cost,reason:'TP'}}let q=side==='BUY'?(c[end].close-e)/r:(e-c[end].close)/r;return{side,entryIndex:j,exit:end,time:c[j].time,r:q-cost,reason:'TIME'}}
function run(c,x,a,b){let o=[],free=a;for(let i=Math.max(a,250);i<Math.min(b,c.length-2);i++){if(i<free)continue;let s=signal(c,i,x);if(!s)continue;let t=trade(c,i,s,x.a[i]);if(t){o.push(t);free=t.exit+1}}return o}
function stats(t){if(!t.length)return{trades:0,wr:0,netR:0,avgR:0,pf:0,dd:0,maxLS:0};let w=0,gw=0,gl=0,e=0,pk=0,dd=0,ls=0,ml=0;for(const x of t){e+=x.r;if(x.r>0){w++;gw+=x.r;ls=0}else{gl+=Math.abs(x.r);ls++;ml=Math.max(ml,ls)}pk=Math.max(pk,e);dd=Math.max(dd,pk-e)}return{trades:t.length,wr:w/t.length*100,netR:e,avgR:e/t.length,pf:gl?gw/gl:999,dd,maxLS:ml}}
const fmt=s=>`${s.trades} trades | WR ${s.wr.toFixed(1)}% | Net ${s.netR>=0?'+':''}${s.netR.toFixed(2)}R | Avg ${s.avgR.toFixed(3)}R | PF ${s.pf.toFixed(2)} | DD ${s.dd.toFixed(2)}R | LS ${s.maxLS}`;
function yearly(t){let m={};for(const x of t){let y=new Date(x.time).getUTCFullYear();(m[y]??=[]).push(x)}return Object.entries(m).sort((a,b)=>a[0]-b[0]).map(([y,a])=>({year:+y,...stats(a)}))}
(async()=>{console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');console.log('⚡ LIQUIDITY SWEEP BASELINE — DUKASCOPY');console.log('XAUUSD | M5 trigger + completed M15 EMA200');console.log(`Params: ${JSON.stringify(P)}`);console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');let raw=await getGoldHistoricalCandles('5min',HISTORY),c=raw.map(r=>({time:+(r.time??r.timestamp),open:+r.open,high:+r.high,low:+r.low,close:+r.close})).filter(r=>[r.time,r.open,r.high,r.low,r.close].every(Number.isFinite));let h15=agg(c),he=ema(h15.map(z=>z.close),200),x={e9:ema(c.map(z=>z.close),9),e21:ema(c.map(z=>z.close),21),a:atr(c),d:adx(c),h:mapHTF(c,h15,he)};let st=250;while(st<c.length&&!Number.isFinite(x.h[st]))st++;let u=c.length-st,de=st+Math.floor(u*.6),ve=st+Math.floor(u*.8);let dev=run(c,x,st,de),val=run(c,x,de,ve),oos=run(c,x,ve,c.length),all=[...dev,...val,...oos];console.log(`\n📊 DEV\n${fmt(stats(dev))}`);console.log(`\n📊 VAL\n${fmt(stats(val))}`);console.log(`\n🧪 OOS — UNTOUCHED 20%\n${fmt(stats(oos))}`);console.log(`\n📈 OOS BUY\n${fmt(stats(oos.filter(t=>t.side==='BUY')))}`);console.log(`\n📉 OOS SELL\n${fmt(stats(oos.filter(t=>t.side==='SELL')))}`);console.log('\n📅 YEARLY — FULL HISTORY');for(const y of yearly(all))console.log(`${y.year} | ${y.trades} | WR ${y.wr.toFixed(1)}% | ${y.netR>=0?'+':''}${y.netR.toFixed(2)}R | PF ${y.pf.toFixed(2)} | DD ${y.dd.toFixed(2)}R`);let file=path.join(OUT,'liquidity-sweep-baseline-dukascopy.json');fs.writeFileSync(file,JSON.stringify({params:P,dev:stats(dev),val:stats(val),oos:stats(oos),oosBuy:stats(oos.filter(t=>t.side==='BUY')),oosSell:stats(oos.filter(t=>t.side==='SELL')),yearly:yearly(all)},null,2));console.log(`\n💾 ${file}`)})().catch(e=>{console.error(e);process.exit(1)});