const {getGoldHistoricalCandles}=require('./backtestHistoryDukascopyLocal');
const H=Math.max(10000,Math.min(100000,Number(process.env.BACKTEST_HISTORY||100000)));
const COST=Number(process.env.COST_PRICE||0.45);
function ema(v,p){let o=Array(v.length).fill(null),a=2/(p+1);if(!v.length)return o;o[0]=v[0];for(let i=1;i<v.length;i++)o[i]=a*v[i]+(1-a)*o[i-1];return o}
function aggregate(c,n){let out=[];for(let i=0;i<c.length;i+=n){let q=c.slice(i,i+n);if(q.length<n)break;out.push({time:q[0].time,open:q[0].open,high:Math.max(...q.map(x=>x.high)),low:Math.min(...q.map(x=>x.low)),close:q[q.length-1].close,end:i+n-1})}return out}
function mapClosed(c,agg){let m=Array(c.length).fill(null),j=-1;for(let i=0;i<c.length;i++){while(j+1<agg.length&&agg[j+1].end<i)j++;m[i]=j}return m}
function stats(t){if(!t.length)return{trades:0,wr:0,netR:0,avgR:0,pf:0,dd:0,ls:0};let w=0,gw=0,gl=0,e=0,pk=0,dd=0,ls=0,ml=0;for(const x of t){e+=x.r;if(x.r>0){w++;gw+=x.r;ls=0}else{gl-=x.r;ls++;ml=Math.max(ml,ls)}pk=Math.max(pk,e);dd=Math.max(dd,pk-e)}return{trades:t.length,wr:100*w/t.length,netR:e,avgR:e/t.length,pf:gl?gw/gl:999,dd,ls:ml}}
const f=s=>`${s.trades} trades | WR ${s.wr.toFixed(1)}% | Net ${s.netR>=0?'+':''}${s.netR.toFixed(2)}R | Avg ${s.avgR.toFixed(3)}R | PF ${s.pf.toFixed(2)} | DD ${s.dd.toFixed(2)}R | LS ${s.ls}`;
function run(c,a,b){const cl=c.map(x=>x.close),e20=ema(cl,20),m15=aggregate(c,3),h1=aggregate(c,12),m15f=ema(m15.map(x=>x.close),50),m15s=ema(m15.map(x=>x.close),200),h1f=ema(h1.map(x=>x.close),50),h1s=ema(h1.map(x=>x.close),200),mm=mapClosed(c,m15),hm=mapClosed(c,h1);let out=[],open=[];const point=.01,dist=1500*point;
 for(let i=Math.max(a,2500);i<Math.min(b,c.length-1);i++){
   let survivors=[];for(const p of open){let age=i-p.i,exit=null;if(p.side==='BUY'){if(c[i].low<=p.sl)exit=p.sl;else if(c[i].high>=p.tp)exit=p.tp}else{if(c[i].high>=p.sl)exit=p.sl;else if(c[i].low<=p.tp)exit=p.tp}if(exit===null&&age>=3){let pnl=p.side==='BUY'?c[i].close-p.entry:p.entry-c[i].close;if(pnl>0)exit=c[i].close}if(exit===null&&age>=12)exit=c[i].close;if(exit!==null){let pnl=p.side==='BUY'?exit-p.entry:p.entry-exit;out.push({side:p.side,time:p.time,r:(pnl-COST)/dist})}else survivors.push(p)}open=survivors;
   if(i+1>=b||open.length>=10)continue;let j15=mm[i],jh=hm[i];if(j15<200||jh<200)continue;let bull=m15f[j15]>m15s[j15]&&h1f[jh]>h1s[jh],bear=m15f[j15]<m15s[j15]&&h1f[jh]<h1s[jh];let buy=bull&&c[i-1].close<e20[i-1]&&c[i].close>e20[i],sell=bear&&c[i-1].close>e20[i-1]&&c[i].close<e20[i];if(!buy&&!sell)continue;let entry=c[i].close,side=buy?'BUY':'SELL';open.push({side,entry,sl:side==='BUY'?entry-dist:entry+dist,tp:side==='BUY'?entry+dist:entry-dist,i,time:c[i].time});
 }
 return out}
(async()=>{console.log('⚡ NonGP33M XAUUSD EA0 — EXACT LOGIC BASELINE');console.log('M5 EMA20 recross | M15+H1 EMA50/200 alignment | SL=TP=1500 points | early profit 15m | max 60m');let c=(await getGoldHistoricalCandles('5min',H)).map(z=>({...z,time:+z.time,open:+z.open,high:+z.high,low:+z.low,close:+z.close}));let s=2500,u=c.length-s,de=s+Math.floor(u*.6),ve=s+Math.floor(u*.8),D=run(c,s,de),V=run(c,de,ve),O=run(c,ve,c.length),F=run(c,s,c.length);console.log('\n📊 DEV\n'+f(stats(D))+'\n\n📊 VAL\n'+f(stats(V))+'\n\n🧪 OOS — UNTOUCHED 20%\n'+f(stats(O)));console.log('\n📈 OOS BUY\n'+f(stats(O.filter(x=>x.side==='BUY'))));console.log('\n📉 OOS SELL\n'+f(stats(O.filter(x=>x.side==='SELL'))));console.log('\n📅 YEARLY — FULL HISTORY');let y={};for(const t of F){let k=new Date(t.time).getUTCFullYear();(y[k]??=[]).push(t)}for(const [k,v] of Object.entries(y))console.log(`${k} | ${f(stats(v))}`)})().catch(e=>{console.error(e);process.exit(1)});