const {getGoldHistoricalCandles}=require('./backtestHistoryDukascopyM1Local');
const H=Math.max(100000,Math.min(1000000,Number(process.env.BACKTEST_HISTORY||1000000))),COST=Number(process.env.COST_PRICE||.45);
const Z=2,MAX_ADX=25,STOP_ATR=1.5,HOLD=90;
function atr(c,n=14){let o=Array(c.length).fill(null),v=null;for(let i=1;i<c.length;i++){let tr=Math.max(c[i].high-c[i].low,Math.abs(c[i].high-c[i-1].close),Math.abs(c[i].low-c[i-1].close));v=v==null?tr:(v*(n-1)+tr)/n;if(i>=n)o[i]=v}return o}
function adx(c,n=14){let N=c.length,tr=Array(N).fill(0),pd=Array(N).fill(0),md=Array(N).fill(0),atrR=Array(N).fill(null),pR=Array(N).fill(null),mR=Array(N).fill(null),dx=Array(N).fill(null),out=Array(N).fill(null),T=null,P=null,M=null,D=null;for(let i=1;i<N;i++){tr[i]=Math.max(c[i].high-c[i].low,Math.abs(c[i].high-c[i-1].close),Math.abs(c[i].low-c[i-1].close));let up=c[i].high-c[i-1].high,dn=c[i-1].low-c[i].low;pd[i]=up>dn&&up>0?up:0;md[i]=dn>up&&dn>0?dn:0;T=T==null?tr[i]:(T*(n-1)+tr[i])/n;P=P==null?pd[i]:(P*(n-1)+pd[i])/n;M=M==null?md[i]:(M*(n-1)+md[i])/n;atrR[i]=T;pR[i]=P;mR[i]=M;if(i>=n&&T>0){let pi=100*P/T,mi=100*M/T;dx[i]=(pi+mi)?100*Math.abs(pi-mi)/(pi+mi):0;if(Number.isFinite(dx[i])){D=D==null?dx[i]:(D*(n-1)+dx[i])/n;if(i>=2*n-1)out[i]=D}}}return out}
function vwap(c){let o=Array(c.length).fill(null),day='',num=0,den=0;for(let i=0;i<c.length;i++){let d=new Date(c[i].time).toISOString().slice(0,10);if(d!==day){day=d;num=den=0}let tp=(c[i].high+c[i].low+c[i].close)/3,w=Math.max(Number(c[i].volume)||0,1);num+=tp*w;den+=w;o[i]=num/den}return o}
function inSession(t){let h=new Date(t).getUTCHours();/* Goldvein source uses broker 10-23; source comments say broker is EET/EEST. Dukascopy is UTC, use 08-21 UTC baseline. */return h>=8&&h<21}
function stats(t){if(!t.length)return{trades:0,wr:0,netR:0,avgR:0,pf:0,dd:0,ls:0};let w=0,gw=0,gl=0,e=0,pk=0,dd=0,ls=0,ml=0;for(const x of t){e+=x.r;if(x.r>0){w++;gw+=x.r;ls=0}else{gl-=x.r;ls++;ml=Math.max(ml,ls)}pk=Math.max(pk,e);dd=Math.max(dd,pk-e)}return{trades:t.length,wr:100*w/t.length,netR:e,avgR:e/t.length,pf:gl?gw/gl:999,dd,ls:ml}}const f=s=>`${s.trades} trades | WR ${s.wr.toFixed(1)}% | Net ${s.netR>=0?'+':''}${s.netR.toFixed(2)}R | Avg ${s.avgR.toFixed(3)}R | PF ${s.pf.toFixed(2)} | DD ${s.dd.toFixed(2)}R | LS ${s.ls}`;
function prep(c){return{A:atr(c),X:adx(c),V:vwap(c)}}
function run(c,x,A,B){let out=[],p=null;for(let i=Math.max(A,40);i<Math.min(B,c.length-1);i++){if(p){let stop=p.side==='BUY'?c[i].low<=p.sl:c[i].high>=p.sl;if(stop){out.push({side:p.side,time:p.time,r:-1-COST/p.risk});p=null;continue}let mean=p.side==='BUY'?c[i].close>=x.V[i]:c[i].close<=x.V[i],timed=i-p.i>=HOLD;if(mean||timed){let px=c[i+1].open,pnl=p.side==='BUY'?px-p.entry:p.entry-px;out.push({side:p.side,time:p.time,r:(pnl-COST)/p.risk});p=null;continue}/* source regenerates stop each held bar from close ±1.5 current ATR */p.sl=p.side==='BUY'?c[i].close-STOP_ATR*x.A[i]:c[i].close+STOP_ATR*x.A[i];continue}
if(!inSession(c[i].time)||!Number.isFinite(x.A[i])||x.A[i]<=0||!Number.isFinite(x.X[i])||x.X[i]>MAX_ADX||!Number.isFinite(x.V[i]))continue;let dist=(c[i].close-x.V[i])/x.A[i],side=dist>Z?'SELL':dist<-Z?'BUY':null;if(!side)continue;let entry=c[i+1].open,risk=STOP_ATR*x.A[i],sl=side==='BUY'?c[i].close-risk:c[i].close+risk;p={side,entry,risk,sl,i:i+1,time:c[i+1].time}}
return out}
(async()=>{console.log('⚡ GOLDVEIN VWAP FADE — NATIVE M1 BASELINE');console.log('Dukascopy XAUUSD M1 | session VWAP | distance 2 ATR | ADX<=25 | stop 1.5 ATR | exit VWAP or 90m | London+NY');let c=(await getGoldHistoricalCandles('1min',H)).map(z=>({...z,time:+z.time,open:+z.open,high:+z.high,low:+z.low,close:+z.close,volume:+z.volume||0})),x=prep(c),s=100,u=c.length-s,de=s+Math.floor(u*.6),ve=s+Math.floor(u*.8),D=run(c,x,s,de),V=run(c,x,de,ve),O=run(c,x,ve,c.length),F=run(c,x,s,c.length);console.log('\n📊 DEV\n'+f(stats(D))+'\n\n📊 VAL\n'+f(stats(V))+'\n\n🧪 OOS — UNTOUCHED 20%\n'+f(stats(O)));console.log('\n📈 OOS BUY\n'+f(stats(O.filter(t=>t.side==='BUY'))));console.log('\n📉 OOS SELL\n'+f(stats(O.filter(t=>t.side==='SELL'))));console.log('\n📅 YEARLY — FULL HISTORY');let y={};for(const t of F){let yr=new Date(t.time).getUTCFullYear();(y[yr]??=[]).push(t)}for(const[yr,v]of Object.entries(y))console.log(`${yr} | ${f(stats(v))}`)})().catch(e=>{console.error(e);process.exit(1)});