const {getGoldHistoricalCandles}=require('./backtestHistoryDukascopyLocal');
const H=Math.max(10000,Math.min(100000,Number(process.env.BACKTEST_HISTORY||100000)));
const COST=Number(process.env.COST_PRICE||0.45),POINT=.01,DIST=1000*POINT;
function ema(v,p){let o=Array(v.length).fill(null),a=2/(p+1);if(!v.length)return o;o[0]=v[0];for(let i=1;i<v.length;i++)o[i]=a*v[i]+(1-a)*o[i-1];return o}
function agg(c,n){let o=[];for(let i=0;i+n<=c.length;i+=n){let q=c.slice(i,i+n);o.push({time:q[0].time,close:q[n-1].close,end:i+n-1})}return o}
function closedMap(c,a){let m=Array(c.length).fill(-1),j=-1;for(let i=0;i<c.length;i++){while(j+1<a.length&&a[j+1].end<i)j++;m[i]=j}return m}
function stats(t){if(!t.length)return{trades:0,wr:0,netR:0,avgR:0,pf:0,dd:0,ls:0};let w=0,gw=0,gl=0,e=0,pk=0,dd=0,ls=0,ml=0;for(const x of t){e+=x.r;if(x.r>0){w++;gw+=x.r;ls=0}else{gl-=x.r;ls++;ml=Math.max(ml,ls)}pk=Math.max(pk,e);dd=Math.max(dd,pk-e)}return{trades:t.length,wr:100*w/t.length,netR:e,avgR:e/t.length,pf:gl?gw/gl:999,dd,ls:ml}}
const f=s=>`${s.trades} trades | WR ${s.wr.toFixed(1)}% | Net ${s.netR>=0?'+':''}${s.netR.toFixed(2)}R | Avg ${s.avgR.toFixed(3)}R | PF ${s.pf.toFixed(2)} | DD ${s.dd.toFixed(2)}R | LS ${s.ls}`;
function prep(c){let e20=ema(c.map(x=>x.close),20),m15=agg(c,3),h1=agg(c,12),m15f=ema(m15.map(x=>x.close),50),m15s=ema(m15.map(x=>x.close),200),h1f=ema(h1.map(x=>x.close),50),h1s=ema(h1.map(x=>x.close),200);return{e20,m15,h1,m15f,m15s,h1f,h1s,mm:closedMap(c,m15),hm:closedMap(c,h1)}}
function signals(c,x,a,b){let s=[];for(let i=Math.max(a,2500);i<Math.min(b,c.length-1);i++){let j=x.mm[i],h=x.hm[i];if(j<200||h<200)continue;let bull=x.m15f[j]>x.m15s[j]&&x.h1f[h]>x.h1s[h],bear=x.m15f[j]<x.m15s[j]&&x.h1f[h]<x.h1s[h];if(bull&&c[i-1].close<x.e20[i-1]&&c[i].close>x.e20[i])s.push({i,side:'BUY',time:c[i].time});else if(bear&&c[i-1].close>x.e20[i-1]&&c[i].close<x.e20[i])s.push({i,side:'SELL',time:c[i].time})}return s}
function run(c,x,a,b){let ss=signals(c,x,a,b),out=[],open=[];let z=0;for(let i=Math.max(a,2500);i<Math.min(b,c.length);i++){let keep=[];for(const p of open){let hitSL=p.side==='BUY'?c[i].low<=p.sl:c[i].high>=p.sl,hitTP=p.side==='BUY'?c[i].high>=p.tp:c[i].low<=p.tp;if(hitSL||hitTP){let gross=hitSL?-1:1;out.push({side:p.side,time:p.time,r:gross-COST/DIST})}else keep.push(p)}open=keep;while(z<ss.length&&ss[z].i===i){if(open.length<10){let q=ss[z],entry=c[i].close;open.push({...q,entry,sl:q.side==='BUY'?entry-DIST:entry+DIST,tp:q.side==='BUY'?entry+DIST:entry-DIST})}z++}}
 return out}
(async()=>{console.log('⚡ NonGP33M EA0 — USER FIXED EXIT');console.log('ENTRY unchanged | TP=1000 points | SL=1000 points | NO early exit | NO time exit | TP or SL only');let c=(await getGoldHistoricalCandles('5min',H)).map(z=>({...z,time:+z.time,open:+z.open,high:+z.high,low:+z.low,close:+z.close}));let x=prep(c),s=2500,u=c.length-s,de=s+Math.floor(u*.6),ve=s+Math.floor(u*.8),D=run(c,x,s,de),V=run(c,x,de,ve),O=run(c,x,ve,c.length),F=run(c,x,s,c.length);console.log('\n📊 DEV\n'+f(stats(D)));console.log('\n📊 VAL\n'+f(stats(V)));console.log('\n🧪 OOS — UNTOUCHED 20%\n'+f(stats(O)));console.log('\n📈 OOS BUY\n'+f(stats(O.filter(t=>t.side==='BUY'))));console.log('\n📉 OOS SELL\n'+f(stats(O.filter(t=>t.side==='SELL'))));console.log('\n📅 YEARLY — FULL HISTORY');let y={};for(const t of F){let yr=new Date(t.time).getUTCFullYear();(y[yr]??=[]).push(t)}for(const [yr,v] of Object.entries(y))console.log(`${yr} | ${f(stats(v))}`)})().catch(e=>{console.error(e);process.exit(1)});