const { getHistoricalRates } = require('dukascopy-node');

const FROM = process.argv[2] || '2024-08-23';
const TO = process.argv[3] || '2026-08-23';

function tf(rows,min){const ms=min*60000,m=new Map();for(const x of rows){const t=Math.floor(x.timestamp/ms)*ms;if(!m.has(t))m.set(t,{timestamp:t,open:x.open,high:x.high,low:x.low,close:x.close,volume:x.volume||0});else{const b=m.get(t);b.high=Math.max(b.high,x.high);b.low=Math.min(b.low,x.low);b.close=x.close;b.volume+=(x.volume||0);}}return [...m.values()].sort((a,b)=>a.timestamp-b.timestamp);}
function prevIndex(rows,ts){let lo=0,hi=rows.length;while(lo<hi){const m=(lo+hi)>>1;if(rows[m].timestamp<ts)lo=m+1;else hi=m;}return lo-1;}
function emaSeries(v,p){const o=Array(v.length).fill(null),k=2/(p+1);let e=v[0];for(let i=0;i<v.length;i++){if(i>0)e=v[i]*k+e*(1-k);if(i>=p-1)o[i]=e;}return o;}
function atrSeries(c,p=14){const o=Array(c.length).fill(null);for(let i=p;i<c.length;i++){let s=0;for(let j=i-p+1;j<=i;j++){const pc=c[j-1].close;s+=Math.max(c[j].high-c[j].low,Math.abs(c[j].high-pc),Math.abs(c[j].low-pc));}o[i]=s/p;}return o;}
function adxSeries(c,p=14){const o=Array(c.length).fill(null),tr=Array(c.length).fill(0),pd=Array(c.length).fill(0),md=Array(c.length).fill(0);for(let i=1;i<c.length;i++){const up=c[i].high-c[i-1].high,dn=c[i-1].low-c[i].low;pd[i]=up>dn&&up>0?up:0;md[i]=dn>up&&dn>0?dn:0;tr[i]=Math.max(c[i].high-c[i].low,Math.abs(c[i].high-c[i-1].close),Math.abs(c[i].low-c[i-1].close));}if(c.length<=p*2)return o;let trN=0,pN=0,mN=0;for(let i=1;i<=p;i++){trN+=tr[i];pN+=pd[i];mN+=md[i];}const dx=Array(c.length).fill(null);for(let i=p;i<c.length;i++){if(i>p){trN=trN-trN/p+tr[i];pN=pN-pN/p+pd[i];mN=mN-mN/p+md[i];}if(trN<=0)continue;const pdi=100*pN/trN,mdi=100*mN/trN,den=pdi+mdi;if(den>0)dx[i]=100*Math.abs(pdi-mdi)/den;}let seed=0,count=0;for(let i=p;i<c.length;i++){if(!Number.isFinite(dx[i]))continue;if(count<p){seed+=dx[i];count++;if(count===p)o[i]=seed/p;}else if(Number.isFinite(o[i-1]))o[i]=(o[i-1]*(p-1)+dx[i])/p;}return o;}
function trendSeries(c){const cls=c.map(x=>x.close),e20=emaSeries(cls,20),e50=emaSeries(cls,50);return c.map((_,i)=>e20[i]>e50[i]?'BUY':e20[i]<e50[i]?'SELL':null);}
function vwapSeries(c,lookback=288){const o=Array(c.length).fill(null);let pv=0,vol=0;const q=[];for(let i=0;i<c.length;i++){const v=Number(c[i].volume)||0,tp=(c[i].high+c[i].low+c[i].close)/3;q.push([tp,v]);pv+=tp*v;vol+=v;if(q.length>lookback){const [otp,ov]=q.shift();pv-=otp*ov;vol-=ov;}o[i]=vol>0?pv/vol:null;}return o;}
function nySession(ts){const p=new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',hour12:false,hour:'2-digit',minute:'2-digit'}).formatToParts(new Date(ts));const h=Number(p.find(x=>x.type==='hour')?.value||0),m=Number(p.find(x=>x.type==='minute')?.value||0),x=h*60+m;return x>=510&&x<720;}
function sim(m5,start,side,entry,sl,tp,maxBars=4320){for(let j=start;j<m5.length&&j<=start+maxBars;j++){const b=m5[j];if(side==='BUY'){if(b.low<=sl)return{r:-1,exit:j};if(b.high>=tp)return{r:(tp-entry)/(entry-sl),exit:j};}else{if(b.high>=sl)return{r:-1,exit:j};if(b.low<=tp)return{r:(entry-tp)/(sl-entry),exit:j};}}return null;}
function stats(name,trades){let net=0,peak=0,dd=0,gp=0,gl=0,w=0,ls=0,maxLs=0;const years={};for(const t of trades){net+=t.r;if(t.r>0){w++;gp+=t.r;ls=0;}else{gl+=Math.abs(t.r);ls++;maxLs=Math.max(maxLs,ls);}peak=Math.max(peak,net);dd=Math.max(dd,peak-net);const y=new Date(t.time).getUTCFullYear();if(!years[y])years[y]={n:0,r:0};years[y].n++;years[y].r+=t.r;}return{name,trades:trades.length,wr:trades.length?w/trades.length*100:0,net,avg:trades.length?net/trades.length:0,pf:gl?gp/gl:Infinity,dd,maxLs,years};}
function print(s){console.log('\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');console.log(`📊 ${s.name}`);console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');console.log(`Trades: ${s.trades}`);console.log(`WR: ${s.wr.toFixed(1)}%`);console.log(`Net R: ${s.net>=0?'+':''}${s.net.toFixed(2)}R`);console.log(`Avg R: ${s.avg.toFixed(3)}R`);console.log(`PF: ${Number.isFinite(s.pf)?s.pf.toFixed(2):'∞'}`);console.log(`DD: ${s.dd.toFixed(2)}R`);console.log(`Max LS: ${s.maxLs}`);console.log('\n📅 Yearly');for(const [y,v] of Object.entries(s.years))console.log(`${y} | ${v.n} | ${v.r>=0?'+':''}${v.r.toFixed(2)}R`);}

function runNY(m5,m15,h1,ind,cfg){const out=[];for(let i=60;i<m5.length-2;i++){const sig=m5[i],entryIdx=i+1;if(!nySession(m5[entryIdx].timestamp))continue;const j15=prevIndex(m15,sig.timestamp+1),j1=prevIndex(h1,sig.timestamp+1);if(j15<55||j1<55)continue;const t15=ind.t15[j15],t1=ind.t1[j1];if(!t15||t15!==t1||!(ind.adx15[j15]>=cfg.adxMin))continue;const atr=ind.a5[i];if(!(atr>0))continue;const ema20=ind.e20[i],vw=ind.vw[i];if(!Number.isFinite(ema20)||!Number.isFinite(vw))continue;const close=sig.close,open=sig.open,chase=Math.min(Math.abs(close-ema20),Math.abs(close-vw))/atr;if(chase>cfg.chaseMax)continue;const recent=m5.slice(i-3,i+1),tol=atr*0.12;const touched=recent.some(x=>(x.low<=ema20+tol&&x.high>=ema20-tol)||(x.low<=vw+tol&&x.high>=vw-tol));if(!touched)continue;const side=t15;if(side==='BUY'&&!(close>open&&(close>=ema20||close>=vw)))continue;if(side==='SELL'&&!(close<open&&(close<=ema20||close<=vw)))continue;const mm=m5.slice(i-2,i+1);let impulse=0,str=0;for(const x of mm){const d=x.close-x.open;impulse+=d;if(d>0)str++;else if(d<0)str--;}const md=impulse>0?'BUY':impulse<0?'SELL':null;if(md!==side||Math.abs(str)<1)continue;if(Math.abs(close-open)/atr>cfg.bodyMax)continue;const entry=m5[entryIdx].open;if(Math.min(Math.abs(entry-ema20),Math.abs(entry-vw))/atr>cfg.chaseMax)continue;const swingRows=m5.slice(Math.max(0,i-11),i+1);const swing=side==='BUY'?Math.min(...swingRows.map(x=>x.low)):Math.max(...swingRows.map(x=>x.high));const rawRisk=side==='BUY'?entry-(swing-atr*0.15):(swing+atr*0.15)-entry,risk=Math.max(rawRisk,atr*0.55);if(!(risk>0))continue;const sl=side==='BUY'?entry-risk:entry+risk,tp=side==='BUY'?entry+risk*cfg.rr:entry-risk*cfg.rr;const z=sim(m5,entryIdx,side,entry,sl,tp);if(!z)continue;out.push({time:m5[entryIdx].timestamp,r:z.r,side});i=z.exit;}return out;}

(async()=>{
 console.log('🗽 NEW YORK — DUKASCOPY QUICK OPTIMIZER');
 console.log(`📅 ${FROM} → ${TO}`);
 console.log('⏳ Loading XAUUSD M5 from Dukascopy...');
 const raw=await getHistoricalRates({instrument:'xauusd',dates:{from:new Date(FROM+'T00:00:00Z'),to:new Date(TO+'T23:59:59Z')},timeframe:'m5',format:'json',volumes:true,batchSize:10,pauseBetweenBatchesMs:500,useCache:true,cacheFolderPath:'./data/dukascopy-cache'});
 const m5=raw.map(x=>({timestamp:+x.timestamp,open:+x.open,high:+x.high,low:+x.low,close:+x.close,volume:+x.volume||0})).filter(x=>[x.timestamp,x.open,x.high,x.low,x.close].every(Number.isFinite)).sort((a,b)=>a.timestamp-b.timestamp);
 const m15=tf(m5,15),h1=tf(m5,60),cls=m5.map(x=>x.close);
 const ind={a5:atrSeries(m5,14),e20:emaSeries(cls,20),vw:vwapSeries(m5,288),adx15:adxSeries(m15,14),t15:trendSeries(m15),t1:trendSeries(h1)};
 console.log(`✅ M5 ${m5.length} | M15 ${m15.length} | H1 ${h1.length}`);
 const configs=[];for(const adxMin of [22,25])for(const chaseMax of [0.35,0.50])for(const rr of [1.0,1.25])configs.push({adxMin,chaseMax,rr,bodyMax:0.35});
 console.log(`🔬 QUICK Variants=${configs.length}`);
 const rows=configs.map((cfg,i)=>{const s=stats(`Candidate ${i+1}`,runNY(m5,m15,h1,ind,cfg));return{cfg,s};}).sort((a,b)=>(b.s.net-b.s.dd*0.35)-(a.s.net-a.s.dd*0.35));
 rows.forEach((x,i)=>{console.log(`\n🥇 Candidate ${i+1}: ${JSON.stringify(x.cfg)}`);print(x.s);});
})().catch(e=>{console.error('❌ NY QUICK ERROR:',e);process.exit(1);});
