require('dotenv').config();
const fs=require('fs'),path=require('path');
const {getGoldHistoricalCandles}=require('./backtestHistoryDukascopyLocal');
const H=Math.max(10000,Math.min(100000,Number(process.env.BACKTEST_HISTORY||100000)));
const SPREAD=Math.max(0,Number(process.env.BACKTEST_SPREAD_USD||.35)),SLIP=Math.max(0,Number(process.env.BACKTEST_SLIPPAGE_USD||.05));
const OUT=path.resolve(process.cwd(),'data','backtests');fs.mkdirSync(OUT,{recursive:true});
const ema=(v,p)=>{let o=Array(v.length).fill(null);if(v.length<p)return o;let s=0;for(let i=0;i<p;i++)s+=v[i];let e=s/p;o[p-1]=e;let k=2/(p+1);for(let i=p;i<v.length;i++){e=v[i]*k+e*(1-k);o[i]=e}return o};
function rsi(v,p=14){let o=Array(v.length).fill(null);if(v.length<=p)return o;let g=0,l=0;for(let i=1;i<=p;i++){let d=v[i]-v[i-1];if(d>=0)g+=d;else l-=d}g/=p;l/=p;o[p]=l===0?100:100-(100/(1+g/l));for(let i=p+1;i<v.length;i++){let d=v[i]-v[i-1],up=d>0?d:0,dn=d<0?-d:0;g=(g*(p-1)+up)/p;l=(l*(p-1)+dn)/p;o[i]=l===0?100:100-(100/(1+g/l))}return o}
function atr(c,p=14){let t=Array(c.length).fill(0),o=Array(c.length).fill(null);for(let i=1;i<c.length;i++)t[i]=Math.max(c[i].high-c[i].low,Math.abs(c[i].high-c[i-1].close),Math.abs(c[i].low-c[i-1].close));let s=0;for(let i=1;i<=p;i++)s+=t[i];let a=s/p;o[p]=a;for(let i=p+1;i<c.length;i++){a=(a*(p-1)+t[i])/p;o[i]=a}return o}
function sma(v,p){let o=Array(v.length).fill(null),s=0;for(let i=0;i<v.length;i++){s+=Number(v[i])||0;if(i>=p)s-=Number(v[i-p])||0;if(i>=p-1)o[i]=s/p}return o}
function stats(t){if(!t.length)return{trades:0,wr:0,netR:0,avgR:0,pf:0,dd:0,maxLS:0};let w=0,gw=0,gl=0,e=0,pk=0,dd=0,ls=0,ml=0;for(const x of t){e+=x.r;if(x.r>0){w++;gw+=x.r;ls=0}else{gl+=Math.abs(x.r);ls++;ml=Math.max(ml,ls)}pk=Math.max(pk,e);dd=Math.max(dd,pk-e)}return{trades:t.length,wr:w/t.length*100,netR:e,avgR:e/t.length,pf:gl?gw/gl:999,dd,maxLS:ml}}
const fmt=s=>`${s.trades} trades | WR ${s.wr.toFixed(1)}% | Net ${s.netR>=0?'+':''}${s.netR.toFixed(2)}R | Avg ${s.avgR.toFixed(3)}R | PF ${s.pf.toFixed(2)} | DD ${s.dd.toFixed(2)}R | LS ${s.maxLS}`;
function makeTrade(c,i,side,a){let j=i+1;if(j>=c.length||!(a>0))return null;let e=side==='BUY'?c[j].open+SLIP:c[j].open-SLIP,sl=side==='BUY'?e-2*a:e+2*a,risk=2*a,cost=(SPREAD+2*SLIP)/risk;
let targets=side==='BUY'?[e+.2,e+.5,e+1]:[e-.2,e-.5,e-1],left=1,real=0,hit=[false,false,false],end=Math.min(c.length-1,j+36);
for(let k=j;k<=end;k++){let b=c[k],hs=side==='BUY'?b.low<=sl:b.high>=sl;if(hs){real+=left*(-1);left=0;return{side,exit:k,r:real-cost}}
for(let q=0;q<3;q++)if(!hit[q]){let ht=side==='BUY'?b.high>=targets[q]:b.low<=targets[q];if(ht){hit[q]=true;real+=(1/3)*((q===0?.2:q===1?.5:1)/risk);left-=1/3;}}
if(left<=1e-9)return{side,exit:k,r:real-cost};}
let px=c[end].close,rr=side==='BUY'?(px-e)/risk:(e-px)/risk;real+=left*rr;return{side,exit:end,r:real-cost}}
function run(c,from,to){let close=c.map(x=>x.close),e9=ema(close,9),e21=ema(close,21),R=rsi(close,14),A=atr(c,14),vs=sma(c.map(x=>x.volume||0),20),out=[],free=from;
for(let i=Math.max(from,25);i<Math.min(to,c.length-2);i++){if(i<free||![e9[i],e21[i],e9[i-1],e21[i-1],R[i],A[i],vs[i]].every(Number.isFinite))continue;let crossUp=e9[i]>e21[i]&&e9[i-1]<=e21[i-1],crossDn=e9[i]<e21[i]&&e9[i-1]>=e21[i-1],vol=(c[i].volume||0)>vs[i]*1.5,side=crossUp&&R[i]>50&&vol?'BUY':crossDn&&R[i]<50&&vol?'SELL':null;if(!side)continue;let t=makeTrade(c,i,side,A[i]);if(t){out.push(t);free=t.exit+1}}return out}
function yearly(c,t){let m={};for(const x of t){let y=new Date(c[x.exit].time).getUTCFullYear();(m[y]??=[]).push(x)}return m}
(async()=>{console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n⚡ GROK GOLD PRO V2 — BASELINE REBUILD\nXAUUSD M5 | Dukascopy\nEMA9/21 crossover + RSI50 + volume spike + ATRx2\nTP stages: +0.20 / +0.50 / +1.00 price\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');let raw=await getGoldHistoricalCandles('5min',H),c=raw.map(r=>({time:+(r.time??r.timestamp),open:+r.open,high:+r.high,low:+r.low,close:+r.close,volume:+r.volume||0})).filter(r=>[r.time,r.open,r.high,r.low,r.close].every(Number.isFinite)).sort((a,b)=>a.time-b.time);let s=30,u=c.length-s,de=s+Math.floor(u*.6),ve=s+Math.floor(u*.8),D=run(c,s,de),V=run(c,de,ve),O=run(c,ve,c.length),F=run(c,s,c.length);console.log('\n📊 DEV\n'+fmt(stats(D)));console.log('\n📊 VAL\n'+fmt(stats(V)));console.log('\n🧪 OOS — UNTOUCHED 20%\n'+fmt(stats(O)));console.log('\n📈 OOS BUY\n'+fmt(stats(O.filter(x=>x.side==='BUY'))));console.log('\n📉 OOS SELL\n'+fmt(stats(O.filter(x=>x.side==='SELL'))));console.log('\n📅 YEARLY — FULL HISTORY');for(const [y,t] of Object.entries(yearly(c,F)))console.log(`${y} | ${fmt(stats(t))}`);fs.writeFileSync(path.join(OUT,'grok-gold-pro-v2-rebuild-dukascopy.json'),JSON.stringify({note:'Rebuild from published description; volume spike assumed > SMA20*1.5; staged exits split equally at +0.20/+0.50/+1.00 price.',dev:stats(D),val:stats(V),oos:stats(O),full:stats(F)},null,2));console.log(`\n💾 ${path.join(OUT,'grok-gold-pro-v2-rebuild-dukascopy.json')}`)})().catch(e=>{console.error(e);process.exit(1)});