require('dotenv').config();
const fs=require('fs'),path=require('path');
const {getGoldHistoricalCandles}=require('./backtestHistoryDukascopyLocal');
const HISTORY=Math.max(10000,Math.min(100000,Number(process.env.BACKTEST_HISTORY||100000)));
const SPREAD=Math.max(0,Number(process.env.BACKTEST_SPREAD_USD||0.35)),SLIP=Math.max(0,Number(process.env.BACKTEST_SLIPPAGE_USD||0.05));
const EMA_LEN=20,RR=2,SWEEP_LOOKBACK=10,MOM_ATR=0.6;
const OUT=path.resolve(process.cwd(),'data','backtests');fs.mkdirSync(OUT,{recursive:true});
function ema(v,p){const o=Array(v.length).fill(null);if(v.length<p)return o;let s=0;for(let i=0;i<p;i++)s+=v[i];let e=s/p;o[p-1]=e;const k=2/(p+1);for(let i=p;i<v.length;i++){e=v[i]*k+e*(1-k);o[i]=e}return o}
function atr(c,p=14){const tr=Array(c.length).fill(0),o=Array(c.length).fill(null);for(let i=1;i<c.length;i++)tr[i]=Math.max(c[i].high-c[i].low,Math.abs(c[i].high-c[i-1].close),Math.abs(c[i].low-c[i-1].close));let s=0;for(let i=1;i<=p;i++)s+=tr[i];let a=s/p;o[p]=a;for(let i=p+1;i<c.length;i++){a=(a*(p-1)+tr[i])/p;o[i]=a}return o}
function agg(c,m){const z=m*60000,o=[];let x=null;for(const r of c){const b=Math.floor(r.time/z)*z;if(!x||x.time!==b){if(x)o.push(x);x={time:b,open:r.open,high:r.high,low:r.low,close:r.close}}else{x.high=Math.max(x.high,r.high);x.low=Math.min(x.low,r.low);x.close=r.close}}if(x)o.push(x);return o}
function mapCompleted(base,higher,vals,m){const out=Array(base.length).fill(null),dur=m*60000;let j=-1;for(let i=0;i<base.length;i++){while(j+1<higher.length&&higher[j+1].time+dur<=base[i].time)j++;if(j>=0&&Number.isFinite(vals[j]))out[i]=vals[j]}return out}
function priorLow(c,i,n){let v=Infinity;for(let k=i-n;k<i;k++)if(k>=0)v=Math.min(v,c[k].low);return v}
function priorHigh(c,i,n){let v=-Infinity;for(let k=i-n;k<i;k++)if(k>=0)v=Math.max(v,c[k].high);return v}
function signal(c,i,x){if(i<SWEEP_LOOKBACK+2||![x.e20[i],x.a14[i],x.h30e20[i]].every(Number.isFinite))return null;const bar=c[i],a=x.a14[i],lo=priorLow(c,i,SWEEP_LOOKBACK),hi=priorHigh(c,i,SWEEP_LOOKBACK),body=bar.close-bar.open,absBody=Math.abs(body);
const sniperBuy=bar.low<lo&&bar.close>lo&&bar.close<x.e20[i]&&bar.close>x.h30e20[i];
const sniperSell=bar.high>hi&&bar.close<hi&&bar.close>x.e20[i]&&bar.close<x.h30e20[i];
const trendBuy=bar.close>x.e20[i]&&bar.close>x.h30e20[i]&&body>0&&absBody>=a*MOM_ATR&&bar.close>c[i-1].high;
const trendSell=bar.close<x.e20[i]&&bar.close<x.h30e20[i]&&body<0&&absBody>=a*MOM_ATR&&bar.close<c[i-1].low;
if(sniperBuy)return{side:'BUY',mode:'SNIPER'};if(sniperSell)return{side:'SELL',mode:'SNIPER'};if(trendBuy)return{side:'BUY',mode:'TREND'};if(trendSell)return{side:'SELL',mode:'TREND'};return null}
function makeTrade(c,i,sig,a){const j=i+1;if(j>=c.length)return null;const entry=sig.side==='BUY'?c[j].open+SLIP:c[j].open-SLIP;let risk;if(sig.mode==='SNIPER')risk=sig.side==='BUY'?entry-(c[i].low-a*0.05):(c[i].high+a*0.05)-entry;else risk=a; risk=Math.max(risk,a*0.5);if(!(risk>0)||risk>a*2)return null;const sl=sig.side==='BUY'?entry-risk:entry+risk,tp=sig.side==='BUY'?entry+risk*RR:entry-risk*RR,costR=(SPREAD+2*SLIP)/risk;return{side:sig.side,mode:sig.mode,entryIndex:j,entry,sl,tp,risk,costR}}
function resolve(c,t,maxBars=36){const end=Math.min(c.length-1,t.entryIndex+maxBars);for(let k=t.entryIndex;k<=end;k++){const b=c[k],hs=t.side==='BUY'?b.low<=t.sl:b.high>=t.sl,ht=t.side==='BUY'?b.high>=t.tp:b.low<=t.tp;if(hs)return{...t,exitIndex:k,resultR:-1-t.costR};if(ht)return{...t,exitIndex:k,resultR:RR-t.costR}}const last=c[end].close,g=t.side==='BUY'?(last-t.entry)/t.risk:(t.entry-last)/t.risk;return{...t,exitIndex:end,resultR:g-t.costR}}
function run(c,x,from,to){const out=[];let free=from;for(let i=Math.max(from,250);i<Math.min(to,c.length-2);i++){if(i<free)continue;const sig=signal(c,i,x);if(!sig)continue;const t=makeTrade(c,i,sig,x.a14[i]);if(!t)continue;const d=resolve(c,t);out.push(d);free=d.exitIndex+1}return out}
function stats(t){if(!t.length)return{trades:0,wr:0,netR:0,avgR:0,pf:0,dd:0,maxLS:0};let w=0,gw=0,gl=0,e=0,pk=0,dd=0,ls=0,ml=0;for(const x of t){const r=x.resultR;e+=r;if(r>0){w++;gw+=r;ls=0}else{gl+=Math.abs(r);ls++;ml=Math.max(ml,ls)}pk=Math.max(pk,e);dd=Math.max(dd,pk-e)}return{trades:t.length,wr:w/t.length*100,netR:e,avgR:e/t.length,pf:gl?gw/gl:999,dd,maxLS:ml}}
const fmt=s=>`${s.trades} trades | WR ${s.wr.toFixed(1)}% | Net ${s.netR>=0?'+':''}${s.netR.toFixed(2)}R | Avg ${s.avgR.toFixed(3)}R | PF ${s.pf.toFixed(2)} | DD ${s.dd.toFixed(2)}R | LS ${s.maxLS}`;
function yearly(c,trades){const m={};for(const t of trades){const y=new Date(c[t.entryIndex].time).getUTCFullYear();(m[y]??=[]).push(t)}return m}
(async()=>{console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n🎯 GOLD SNIPER PRO — BASELINE REBUILD\nXAUUSD M5 | Dukascopy | 30m filter | RR 2.0\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');const raw=await getGoldHistoricalCandles('5min',HISTORY),c=raw.map(r=>({time:+(r.time??r.timestamp),open:+r.open,high:+r.high,low:+r.low,close:+r.close})).filter(r=>[r.time,r.open,r.high,r.low,r.close].every(Number.isFinite));const h30=agg(c,30),x={e20:ema(c.map(z=>z.close),EMA_LEN),a14:atr(c,14),h30e20:mapCompleted(c,h30,ema(h30.map(z=>z.close),EMA_LEN),30)};let st=250;while(st<c.length&&!Number.isFinite(x.h30e20[st]))st++;const usable=c.length-st,de=st+Math.floor(usable*0.6),ve=st+Math.floor(usable*0.8);const devT=run(c,x,st,de),valT=run(c,x,de,ve),oosT=run(c,x,ve,c.length),all=[...devT,...valT,...oosT];console.log('\n📊 DEV\n'+fmt(stats(devT)));console.log('\n📊 VAL\n'+fmt(stats(valT)));console.log('\n🧪 OOS — UNTOUCHED 20%\n'+fmt(stats(oosT)));console.log('\n🟢 SNIPER FULL\n'+fmt(stats(all.filter(t=>t.mode==='SNIPER'))));console.log('\n🔵 TREND FULL\n'+fmt(stats(all.filter(t=>t.mode==='TREND'))));console.log('\n📈 BUY FULL\n'+fmt(stats(all.filter(t=>t.side==='BUY'))));console.log('\n📉 SELL FULL\n'+fmt(stats(all.filter(t=>t.side==='SELL'))));console.log('\n📅 YEARLY — FULL HISTORY');for(const [y,t] of Object.entries(yearly(c,all)))console.log(`${y} | ${fmt(stats(t))}`);const file=path.join(OUT,'gold-sniper-pro-baseline-dukascopy.json');fs.writeFileSync(file,JSON.stringify({strategy:'Gold Sniper Pro published-logic rebuild',params:{ema:EMA_LEN,rr:RR,sweepLookback:SWEEP_LOOKBACK,momentumAtr:MOM_ATR},dev:stats(devT),val:stats(valT),oos:stats(oosT),sniper:stats(all.filter(t=>t.mode==='SNIPER')),trend:stats(all.filter(t=>t.mode==='TREND'))},null,2));console.log(`\n💾 ${file}`)})().catch(e=>{console.error(e);process.exit(1)});